### ISSUE TITLE
cannot delete message after DequeueCount >= MaxDequeueCount

### ISSUE THREAD

**Issue by YangLi01** [Azure/azure-webjobs-sdk#1088]
At QueueProcessor.cs CompleteProcessingMessageAsync method

                if (message.DequeueCount >= MaxDequeueCount)
                {
                   //The following method may change message popReceipt and cause DeleteMessageAsync fail.
                    await CopyMessageToPoisonQueueAsync(message, _poisonQueue, cancellationToken);
                    await DeleteMessageAsync(message, cancellationToken);
                }

Can we create a new message object to copy to poison queue instead of using the original one?

Thanks,
Yang

**Comment by christopheranderson** [comment]
Could you confirm what version of the Azure Storage SDK you're using? We suspect it is 8+, which we don't support at the moment.

**Comment by YangLi01** [comment]
<package id="WindowsAzure.Storage" version="8.1.1" targetFramework="net452" />
Nuget cannot understand this dependence.

**Comment by YangLi01** [comment]
package id="WindowsAzure.Storage" version="8.1.1" targetFramework="net452"

**Comment by christopheranderson** [comment]
Blocked by this issue: https://github.com/Azure/azure-webjobs-sdk/issues/1091

**Comment by fabiomaulo** [comment]
Is this issue fixed in 2.1.0-beta1 ?
Thanks.

**Comment by brettsam** [comment]
The original issue tracking this was #985, which has been fixed. But it was not in time for 2.1.0-beta1. It is available in our nightly drops: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds.

**Comment by fabiomaulo** [comment]
Ok... 2.1.0-beta2 ;)

**Comment by davidmatson** [comment]
I've seen this case with the following symptoms:
1. The message fails processing, and the poison message can't be deleted.
2. Because the poison message can't be deleted, the original message gets processed again. This occurs an unbounded number of times (I've seen 40+).
3. Each time the message fails, an new copy gets added to the poison message queue, but again the original message can't be deleted.

Net, we effectively get stuck in an infinite loop processing a message that keeps creating more poison copies of itself.

**Comment by paulbatum** [comment]
So 2.1.0-beta4 is the release with this fix: https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.1.0-beta4
