### ISSUE TITLE
Storage emulator with WindowsAzure.Storage 8.2.0 cannot work together.

### ISSUE THREAD

**Issue by melenaos** [Azure/azure-webjobs-sdk#1233]
I updated WindowsAzure.Storage to the latest version 8.2.0 and it stoped working with the emulator returning the following message:
`Invalid storage account 'devstoreaccount1'. Please make sure your credentials are correct. `

**Comment by paulbatum** [comment]
We do not officially support using the storage emulator. Also if you are on webjobs 2.x then upgrading to storage 8.x is also not supported (you would need to move to 3.x if you want storage 8.x - please note that 3.x is still under active development and is in beta).

Closing as answered, please reactivate if you additional context to share.

**Comment by dabutvin** [comment]
@paulbatum is this still the case with the latest release?

If I upgrade to `Microsoft.Azure.WebJobs 2.1.0` should I keep `WindowsAzure.Storage 7.2.1`?

The reason I ask is, one of my dependencies requires `WindowsAzure.Storage 8.1.4` and I am trying to use it from a webjob running 2.X

Thanks

**Comment by paulbatum** [comment]
Correct, webjobs 2.1.0 still uses the same version of storage.

I should note that in the last 9 months or so since this issue was closed, we have been more supportive of using the azure storage emulator with functions. You might notice for example that this is the default when making a new function app in Visual Studio.
