### ISSUE TITLE
Application Insights: Incorrect instrumentation key configuration fails silently

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-webjobs-sdk#1235]
I mistakenly used an API key for the APPINSIGHTS_INSTRUMENTATIONKEY setting instead of using the instrumentation key. The result was no data written to my AI instance. There was also nothing in my host logs indicating a problem.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a function app
2. Create an AI instance
3. Create an API key for the AI instance
4. Add the APPINSIGHTS_INSTRUMENTATIONKEY app setting and point it to the API key

#### Expected behavior

Some kind of error indicating that I used an invalid instrumentation key. At a minimum I would expect this to show up in host logs.

#### Actual behavior

No errors. I had to figure this out by guessing possible reasons why my App Insights integration was not working.

**Comment by paulbatum** [comment]
As far as I'm aware, its by design that the app insights sdk silently no-ops when given an invalid instrumentation key. However we could make our portal able to detect an invalid configuration (because there is an API we can use to lookup an appinsights resource by instrumentation key) so that it can show an appropriate warning. @christopheranderson perhaps we should open a new issue against the portal?
