### ISSUE TITLE
Support loading from appsettings.{env}.json

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk#1254]
When I run locally, I like to have another config file which has my secrets in it for dev. 

If we could add this support here: https://github.com/Azure/azure-webjobs-sdk/blob/e915ee574136207cab3b01cac7139bf09b013ace/src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs#L35

We could add:

```csharp
.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
```

which is similar to how ASP.NET does config.

**Comment by paulbatum** [comment]
Also shouldn't environment variables take precedence over this file? I think that would be consistent behavior with functions. Of course this would be a breaking change so we could only do it in 3.x.

**Comment by TheBeardedLlama** [comment]
this is already sorted in #1408 @paulbatum so this ticket can be closed

**Comment by paulbatum** [comment]
@TheBeardedLlama thanks for the ping on this! Closing.

**Comment by TheBeardedLlama** [comment]
you're most welcome @paulbatum 

I stumbled on this while looking for something else

**Comment by rsuk** [comment]
Although the issue with ordering of AddJsonFile and AddEnvironmentVariables has been fixed, the original issue (supporting a second .json file named for the current environment) is still something that would be very useful. Because of the way the ConfigureWebJobs code is structured, it isn't possible to add this in to the default ConfigureWebJobs() between the default appsettings and the environment variables without overriding everything. Seems like a second .AddJsonFile call as proposed in the original comment would be really useful - e.g.

```
config.AddJsonFile("appsettings.json", optional: true);
config.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
```
