### ISSUE TITLE
Azure docs redirects to GitHub Wiki

### ISSUE THREAD

**Issue by nagytech** [Azure/azure-webjobs-sdk#1348]
Not sure if this team has any control over the docs.microsoft.com content, but I'm not sure where else to report the issue.  The URL given below used to link to a good tutorial and sample code, but is now being redirected to the wiki of this repo.  

#### Repro steps

1. Navigate to https://docs.microsoft.com/en-us/azure/app-service-web/websites-dotnet-webjobs-sdk-get-started

#### Expected behavior

Expected that the app-service-web documentation is loaded.

#### Actual behavior

Site redirects to GitHub Wiki.

#### Known workarounds

Use Google cache, or interrupt the redirect.

**Comment by paulbatum** [comment]
@tdykstra I think this is deliberate, right? Was the content that was previously at this link removed for some reason?

**Comment by tdykstra** [comment]
@syntaxc4 FYI

The problem with that article is it was out of date, we prioritized other things over updating it, and the policy in such cases is to take down the content and redirect its URL to the next best resource. In this case, the redirect goes to the wiki because the other WebJobs SDK docs are there now.  They were put there as a temporary home until we update them and integrate them with the Functions docs that share some of the same functionality.  

That said, the WebJobs SDK get started tutorial still exists in Git history and can be found by going to a commit earlier than the one that deleted it. For example it's here:
https://github.com/MicrosoftDocs/azure-docs-pr/blob/c38dad469c17e1de37399da28bebabc06a8940b7/articles/app-service-web/websites-dotnet-webjobs-sdk-get-started.md
