### ISSUE TITLE
Incorrect WEBSITE_HOSTNAME when using slots

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-webjobs-sdk#1369]
Please provide a succinct description of the issue.

#### Repro steps
Create three slots, `context.log(process.env['WEBSITE_HOSTNAME'])` on each

#### Expected behavior
Correct host name.

#### Actual behavior
Incorrect host name.

#### Known workarounds
None, this is causing headaches as I use the hostname to detect which environment the code is running in.

**Comment by paraspatidar** [comment]
The Environment variable **WEBSITE_HOSTNAME** works as a sticky slot setting for Azure Web Apps and remains with that perticular slot even after the Slot Swap.
However Being Azure Function App **Slot** in Preview as of Dated comment , it may not be working.

The work around for the same is as follows any of the one below : 
1.	Use the variable “**WEBSITE_SLOT_NAME**”  , this is reliable and gives the slot name correct (like Production/Stage/Dev or whatever the name of slot), however it doesn’t give the url like WEBSITE_HOSTNAME gives mywebappname-slot.azurewebsites.net.

2.	Use the App setting’s Sticky setting , by marking them as sticky to slot , that will not swap with the slot , it will be stick to that slot only  (in function App , you will need to go to All setting --> App setting and check the slot setting check box) refer [:](https://docs.microsoft.com/en-us/azure/app-service/web-sites-staged-publishing)

3.Alternatively , while using WEBSITE_HOSTNAME , you can restart your function app after the slot swap , it might work.

**Comment by paulbatum** [comment]
Its a general app service issue that you cannot use WEBSITE_HOSTNAME reliably once slots are in play. Use the hostname environment variable in combination with WEBSITE_SLOT_NAME.

**Comment by MikeyF-Anovia** [comment]
As mentioned in https://github.com/Azure/azure-webjobs-sdk/issues/2121, WEBSITE_SLOT_NAME is not an option. I'm running into this issue as well. I have two slots, a continuous webjob runs on both. On the prod slot it runs normally. One the deployment slot it runs and exits because it sees '-deployment' in WEBSITE_HOSTNAME. Once I swap the two, the webjob that was previously in the deployment slot that is now in the prod slot still thinks its in the deployment slot. 

The webjob continuously logs, over and over, these sets of events:
[08/10/2023 20:56:04 > e7cfa4: SYS INFO] Status changed to PendingRestart
[08/10/2023 20:57:04 > e7cfa4: SYS INFO] WebJob singleton lock is released
[08/10/2023 20:57:04 > e7cfa4: SYS INFO] WebJob singleton lock is acquired
[08/10/2023 20:57:04 > e7cfa4: SYS INFO] Run script 'script.php' with script host - 'PhpScriptHost'
[08/10/2023 20:57:04 > e7cfa4: SYS INFO] Status changed to Running
[08/10/2023 20:57:05 > e7cfa4: INFO] Not running on Deployment slot
[08/10/2023 20:57:05 > e7cfa4: SYS INFO] Status changed to Success
[08/10/2023 20:57:05 > e7cfa4: SYS INFO] Process went down, waiting for 60 seconds
[08/10/2023 20:57:05 > e7cfa4: SYS INFO] Status changed to **PendingRestart**

Restarting the web app fixes it. But a big selling point of using slot swapping is to not have to restart. I've swapped slots several times in the past after a deployment and woke up at 3am remembering that I forget to restart the web app to work around this crazy issue. Very irritating. 

Oddly enough, using a custom App Setting on both slots and setting them to sticky does seem to work. I had expected it to run into the same issue but it appears to work. 

Its so much fun losing several hours of my life to this kinda of thing.

**Comment by gioce90** [comment]
So there is no solution at all?
