### ISSUE TITLE
Azure function service bus binding behavior

### ISSUE THREAD

**Issue by dewanymca** [Azure/azure-webjobs-sdk#1482]
Hi Team

We have been using Azure Service Bus trigger for our function app and seeing weird behavior while doing perf test. Below are setting on sb side:
•	Max Delivery Count=1 as I  don’t want to retry.
•	Lock Duration on Service Bus is 5 minutes(max allowed I think).
•	Custom Telemetry enabled in function app for different milestone.
Once message get successfully processed, we put same message in another topic and create a record in Document DB.

Under load test with 2 user and running it for 5 minute, around 3k message got generated. However every time I see 50 message in deadletter but at same time next topic and document db show it as successfully processed for these deadletter message. Telemetry also says that everything went fine and there were no error. So, I am unable to figure out why message will end up in deadletter. It should be successfully deleted by Azure function run time.

I didn’t specify any custom configuration for concurrent calls, locktime out in host.json. Also funcapp is running in ASP.

Please help.

Thanks
Deepak Sanghi

**Comment by christopheranderson** [comment]
Hey @dewanymca, sorry we didn't get to this sooner. Could you share info about your Function app with us? https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately

This is the kind of issue we'd recommend opening a support ticket for, FYI, since some of the debugging information is time sensitive (expires in ~30 days). GitHub has no SLA for support, so we might take too long.
