### ISSUE TITLE
AccessRights are now missing in ServiceBusTriggerAttribute parameters

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-webjobs-sdk#1509]
I'm trying to migrate from `Microsoft.Azure.WebJobs.ServiceBus 2.1.0` to `Microsoft.Azure.WebJobs.ServiceBus 3.0.0-beta4` in my azure function project. And I see that support for `AccessRights` parameter was dropped in this version. Does it mean that now in order to use `ServiceBusTrigger` azure function connection should have access right `manage`? Can someone give some explanation?

**Comment by NatMarchand** [comment]
The webjob extension is now based on the new package Microsoft.Azure.ServiceBus which does not handle queue management at all. The responsibilites are split between managing and using resources.

**Comment by Badabum** [comment]
@NatMarchand I'm talking about queue management at all. My function intends only to be triggered by the message enqueued in the queue. From what I see now, the service bus queue triggered function should define `"accessRights": "listen"` property in `function.json` if the passed ServiceBus connection string has only `Listen` access right. Before the `3.0.0-beta4` version there was the parameter `accessRights` in the constructor of `ServiceBusTriggerAttribute` class which then was converted in the mentioned property in the `function.json`. Now, there is no such parameter, and the resulting `function.json` does not contain `accessRights` property at all.

**Comment by NatMarchand** [comment]
You can have a look in the code but the only usage of the accessRight was if the queue does not exist and accessRight is Manage, then create it. See https://github.com/Azure/azure-webjobs-sdk/blob/ff08a455d838829c9c57cf68ac8679ba1cb5996e/src/Microsoft.Azure.WebJobs.ServiceBus/Bindings/MessageSenderExtensions.cs#L16
Now, as the library under does not allow to create queue (or manage them), then the parameter is not useful anymore.

**Comment by Badabum** [comment]
I see your point, thanks for the link. But it seems that now if I will go to ServiceBus Shared Access Signatures tab and create new with only `Listen` rights and then pass newly created connection string to azure function, the function will not be able to retrieve any messages from the queue

**Comment by NatMarchand** [comment]
There were some issues remaining with service bus in 3.0.0-beta4 till this issue was closed #1329 
There's no new packages yet on nuget available but you might try to grab the artifacts of this build https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-rqm4t/build/3.0.11131/artifacts

**Comment by brettsam** [comment]
@alrod can correct me if I'm wrong.

@NatMarchand  is right that we no longer have queue management operations -- because the .NET Standard versions of the Service Bus libraries removed the APIs that we were previously using. Without that, the AccessRights parameter wasn't needed anymore.

I went ahead and published build [11131 to our myget feed](https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.ServiceBus). You can use this feed by following the directions here: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds

I'm going to close this issue -- feel free to reopen if you're still blocked by this latest package.
