### ISSUE TITLE
Dashboard glitches when multiple WebJobs use the same Azure storage account

### ISSUE THREAD

**Issue by tmenier** [Azure/azure-webjobs-sdk#1541]
#### Scenario
- 2 Web Apps (In my case, 2 slots of the same app. Let's call them `myapp` and `myapp-staging`)
- Each app has 1 active WebJob, and they are uniquely named (call them `wj-prod` and `wj-staging`)
- Each WebJob contains 1 Function, and they are named the same (very common if dealing with multiple slots of the same app)
- Both WebJobs use the same storage account, i.e. `AzureWebJobsStorage` and `AzureWebJobsDashboard` settings are identical
- I'm on version 2.0.0 of both `Microsoft.Azure.WebJobs` and `Microsoft.Azure.WebJobs.Extensions`

#### Bugs/Observations
1. On the main dashboard page for one of the jobs (i.e. https://myapp.scm.azurewebsites.net/azurejobs/#/jobs/continuous/wj-prod), the "Functions invoked" list shows invocations for both wj-prod and wj-staging. Clearly this should only show invocations of wj-prod.
2. Similarly, on the Functions page (link on top right nav, i.e. https://myapp.scm.azurewebsites.net/azurejobs/#/functions), the "Invocation Log" on the right shows invocations from both WebJobs. This also seems incorrect, because a) we are clearly under the context of `myapp` (as indicated by the URL), and the other function exists in a WebJob under `myapp-staging`, and b) the "Functions" list on the left seems to correctly list just functions in `wj-prod`.
3. Sometimes when I run a job manually, the invocation log shows 2 instances of it running.
4. On several occasions I observed invocations listed with status "Running", yet when drilling in the status says "Never finished". (May not be related to the shared storage account but thought I'd mention it anyway.)
5. "Functions" as a top-level nav item is odd. Judging by the URL (/azurejobs/#/functions), this page could reflect functions living in multiple WebJobs of the same app, and there's no guarantee that function names are unique across WebJobs. Yet neither the "Functions" list nor the "Invocation Log" list indicates the WebJob that the listed function belongs to. (They simply say `Functions.MyFunction`, for example.)

I suspect somewhere in the code, and possibly in the blob structure backing the views, an incorrect assumption is made that a function name is unique within the context of the entire blob, regardless of how many WebJobs or even apps might be pointed at it.

**Comment by fabiocav** [comment]
@MikeStall can you comment here?

**Comment by mathewc** [comment]
When you share a storage account between two different WebApps (in your case prod and stage slots) all the logs are going to the same storage account. When you open the Dashboard from each site, since you're pointing to the same storage account, ALL invocations are going to be show. Invocations ARE separated by HostID (as in JobHostConfiguration.HostID), however if you're running the same exe host in both slots, by default they'll have the same HostID (host ID by default is derived from the fully qualified assembly name of the exe or dll where jobs are defined). 

So to answer your questions:

1) This is by design. Invocations aren't filtered by site used to host the Dashboard - the Dashboard will show all invocations stored in the storage account
2) Expected based on 1
3) Perhaps what is happening here is you have the WebJobs running in both slots at the same time? You probably don't want that. You could either use a different storage account for prod and stage (a great practice anyways), or you could ensure that a different HostID is used by your staging slot. E.g. you can conditionally set JobHostConfiguration.HostID to a slot specific value based on a slot setting. See the HostID related comments in https://github.com/Azure/azure-webjobs-sdk-extensions/issues/56 and issues it links to for details.
4) If functions of the same name exist that isn't a problem per say, since internally the name used is fully qualified by HostID. You can see that name in the URLs when navigating.

**Comment by tmenier** [comment]
@mathewc,

Thank you for the reply. Respectfully, if the storage account dictates the scope of what you see listed in the invocations log, even when that conflicts with the what the UI and URL are clearly telling me, and that is by design, then I have to question the design a little. The storage account seems like an implementation detail. Not to sound repetitive, but if I go to the Azure portal and click into a specific app/slot (let's say `myapp-staging`), then a specific WebJob (`wj-staging`), then click Logs, I go here:

https://myapp-staging.scm.azurewebsites.net/azurejobs/#/jobs/continuous/wj-staging

Based on both the UI navigation to get there, and the URL itself, it seems logical/intuitive to expect that I would only see invocations related to `wj-staging` in app/slot `myapp-staging`, even if other apps/jobs are sharing the storage account. Wouldn't you agree?

For me the work-around was simple - I just created a separate storage account for the other job. But it doesn't seem like it should be necessary to create a new billable item for this. Maybe doing things differently with HostIDs would also solve it - I didn't looked into that. But I think my point is valid regardless.

**Comment by mathewc** [comment]
Yes, perhaps the extraneous "wj-staging" on the URL is misleading. Anyhow, I've explained the way things work now, sorry for any confusion this may have caused you.
