### ISSUE TITLE
Access violation: System.AccessViolationException at EdgeJs.Edge.NodeStartx86

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-webjobs-sdk#1612]
The issue reported by customer 

[PROBLEM DESCRIPTION]
The customer has NodeJS functions running in a Standard Plan in the V1 Runtime: 1.0.11535.0. The Functions has been bundled using funcpack. 

Some of the executions are failing with 502.3 with 12030 as win32 error. The error is only logged in the FrontEnd table. It seems to make sense since looking in the Eventlog (attached) we can see that the process in crashing due to an unhandled exception (System.AccessViolationException) coming from the Runtime (EdgeJS). See exception in the Troubleshooting part.

The issue is happening in this environment but they are facing it in other data centers as well.

In the eventlogs.xml we can see this exception several times:

<Event><System><Provider Name=".NET Runtime"/><EventID>1026</EventID><Level>1</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2018-03-01T15:11:39Z"/><EventRecordID>595565281</EventRecordID><Channel>Application</Channel><Computer>RD0003FF4B49C0</Computer><Security/></System><EventData><Data>Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at EdgeJs.Edge.NodeStartx86(Int32, System.String[])
   at EdgeJs.Edge+&lt;&gt;c__DisplayClass2.&lt;Func&gt;b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data></EventData></Event>

[ASK FOR PG]
Kindly check the reason of the 502.3/process crashes as this seems to come from the Runtime.

**Comment by pragnagopa** [comment]
Accessviolation exceptions, generally indicate an application issue. Take a look at [Sandbox restrictions](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) and check if the application is using any of the restricted modules.

**Comment by FinVamp1** [comment]
I looked further into this.

The customer is running into this issue because the Host is shutting down because the other Function <xxxxxxx>  is regularly exceeding their 10 minute timeout.

E.G

Host.Json

{
  "functionTimeout": "00:10:00",
  "http": {
    "routePrefix": ""
  }
}


Timeout value of 00:10:00 exceeded by function 'Functions.<xxxxxxx>' (Id: 'a0f69461-b69a-4e23-bbf6-8253eede90fd'). Initiating cancellation. 

From https://github.com/Azure/azure-functions-host/issues/2367 

"In certain situations the runtime initiates a host shutdown via HostingEnvironment.InitiateShutdown, for example when an unhandled global exception occurs, when a function TimeoutException is thrown, or when performance counter thresholds are exceeded (HostHealthMonitor). This results in a new AppDomain being created in the same process.
When the FunctionApp includes Node.js functions, this AppDomain recycling can trigger the existing known issue reported here, resulting in AccessViolations like the following when a new host is initialized in the new AppDomain”

So the solution here is to look at lambda-warmer to see if it can be re-written to stop the Host shutting down.

**Comment by pragnagopa** [comment]
Yes. This same issue as [Azure/azure-functions-host#2367](https://github.com/Azure/azure-functions-host/issues/2367). Closing this one as it's a won't fix
