### ISSUE TITLE
Azure Function stops working after upgrading to 2.2.0 from 2.1.0

### ISSUE THREAD

**Issue by avoxm** [Azure/azure-webjobs-sdk#1662]
I have an existing azure function that uses ServiceBusTrigger binding to receive messages from a topic subscription.
While using v 2.1.0 with Microsoft.NET.Sdk.Functions 1.0.11 it is working perfectly fine but after upgrading to v 2.2.0 when running function locally it is not able to find the function.

#### Repro steps

Here is simple code that works fine with 2.1.0

```
public static class SampleFunction
{
    [FunctionName("SampleFunction")]
    public static void Run([ServiceBusTrigger("sampletopic", "sample-subscription", AccessRights.Listen, Connection = "MyConnectionString")]string message,
    ILogger log)
    {
        log.LogInformation($"{message} received");
    }
}
```

#### Expected behavior

Should print the messaged published in **sampletopic**.

#### Actual behavior

When running the function here is what I can see in func.exe 

`No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
`
#### Related information 
Provide any related information 

* Working Package version
Microsoft.Azure.WebJobs.ServiceBus (2.1.0)
Microsoft.NET.Sdk.Functions (1.0.11)

* The Package version that break it 
Microsoft.Azure.WebJobs.ServiceBus (2.2.0)
Microsoft.NET.Sdk.Functions (1.0.13)

**Comment by paulbatum** [comment]
I can't reproduce this, but perhaps its because your version of azure-functions-core-tools (used by VS when you F5) is different from mine. Can you check the line of output where it tells you the host version? Mine looks like this:

```
[4/16/2018 6:44:08 PM] Starting Host (HostId=pbatumhost-830666132, Version=1.0.11612.0
```

If the version is older than 1.0.11612.0 then you probably need to update. VS is supposed to prompt you to download the update automatically.

**Comment by paulbatum** [comment]
I should clarify, I couldn't get your code to compile because it was using type `Logger` which I switched to `ILogger`.

**Comment by paulbatum** [comment]
There are manual steps but they are pretty nasty.. can you first check the tools version using these steps:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#check-your-tools-version

**Comment by brandondahler** [comment]
I just had a fun time with the ILogger type the other day.  One thing you might want to check is if you have a reference to Microsoft.Extensions.Logging.Abstractions > 1.1.1 .  

If so, you could be getting a version mismatch where your code is referencing/loading Microsoft.Extensions.Logging.Abstractions > 1.1.1 while the Azure Functions runtime is referencing Microsoft.Extensions.Logging.Abstractions = 1.1.1 .  

Because of how functions are loaded/executed, it is possible to load multiple versions of the same assembly (my case was Microsoft.Extensions.Logging.Abstractions 1.1.1 and Microsoft.Extensions.Logging.Abstractions 2.1.0).  This can result in funny stuff where parameterInfo.ParameterType is `Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions, Version=2.1.0, ...` and they are comparing it to typeof(ILogger) that is actually `Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions, Version=1.1.1, ...`, resulting in `parameterInfo.ParameterType == typeof(ILogger)` to return false.  

The particular line I'm referencing is https://github.com/Azure/azure-webjobs-sdk/blob/5140983cb163b20bf6af60afccebb705bc80ad80/src/Microsoft.Azure.WebJobs.Host/Bindings/ILogger/ILoggerBindingProvider.cs#L31 .


This could all be fixed with binding redirects, but the exact details of all of that are still in limbo at this time.

**Comment by avoxm** [comment]
@paulbatum my appologies for the late reply, I was distracted for a while.

So it looks like the tools version I got is : 15.0.40405.0. Attaching the image bellow.

![image](https://user-images.githubusercontent.com/10351071/38911395-f885bec2-429c-11e8-82c9-9fe6ad2ea695.png)

**Comment by avoxm** [comment]
@brandondahler I've just checked the project. I do not have direct reference to **Microsoft.Extensions.Logging.Abstractions**, but both **Microsoft.Azure.WebJobs.ServiceBus (2.2.0)** and 
**Microsoft.NET.Sdk.Functions (1.0.13)** have dependency on **Microsoft.Extensions.Logging.Abstractions (1.1.1)**.
Based on your description I guess this should not be an issue, right?

**Comment by paulbatum** [comment]
Well, `15.0.40405.0` is the latest released version right now. So I'm not sure why your core tools have not been updated. Tagging @vijayrkn to see if he has any suggestions on how to force the update.

**Comment by avoxm** [comment]
OK thanks @paulbatum. I'll roll back to older version till hopeful this issue will be fixed.
@vijayrkn I'll wait for an update from you and please let me know if there's any more data needed from my end.

**Comment by vijayrkn** [comment]
@avoxm Can you rename this folder - `%localappdata%\Azure.Functions.V2.Cli ` & try running the Functions project from VS. This should force another download of the core tools.

**Comment by avoxm** [comment]
@vijayrkn actually there is no `Azure.Functions.V2.Cli` folder. I have `Azure.Functions.Cli`. 
I can rename that and see.

**Comment by avoxm** [comment]
Ok so renaming the folder forced VS to download the tools SDK and it pulled the latest version. 
It looks like that fixed the problem. Just a note though even after renaming VS still did not prompt an update in `Extensions and Updates` window.
So it seems that the issue is there. 

Thanks everyone for your time and support. Please allow this issue to be here for another 24h, I'd like to test it thoroughly to make sure that it works. I'll post an update if I'll see any issues.

**Comment by avoxm** [comment]
Ok everything seems to be fine now. I'm closing the issue. Thanks for your help guys.

**Comment by vijayrkn** [comment]
>Just a note though even after renaming VS still did not prompt an update in Extensions and Updates window. So it seems that the issue is there.

15.0.40405.0 is still the latest version. That is the reason you didnt get prompted for an update. But looks like something stopped the core tools from getting updated. We will take a look at that issue.
