### ISSUE TITLE
Usage of ConfigurationUtility should be discontinued

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk#1841]
The `ConfigurationUtility` class does not work with the configuration system and doesn't take the current configuration into consideration. Code using the type should be updated and the class should be removed.

**Comment by brettsam** [comment]
FYI -- this is only used in a couple of places today. A little effort and we should be able to knock this out.

**Comment by kierono** [comment]
Is there an update on this?

**Comment by brettsam** [comment]
@kierono -- this is an internal class and this item was for some internal cleanup. Can you explain how it's impacting you?

**Comment by kierono** [comment]
The issue we have experienced is with running a webjob with .Net Framework 4.7.2 and how the [DisableAttribute](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs/DisableAttribute.cs) is used from [HostListenerFactory](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Listeners/HostListenerFactory.cs).

We use the attribute and pass in a settingName to configure whether a function should be disabled. 
```csharp
public DisableAttribute(string settingName)
{
    SettingName = settingName;
}
```
In v2 of the sdk this would be read from app.config, in v3, we thought it would be from the configuration passed in to HostBuilder. The first workaround was to write a ConfigurationProvider that could read from app.config instead of appsettings.json. This worked successfully with other settings e.g. AzureWebJobStorage but still not for DisableAttribute.

Looking through the source, we saw that HostListenerFactory, when it calls in to [ConfigurationUtlity](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs), it doesn't use the configuration given to the HostBuilder but instead only uses environment variables and appsettings.json, neither of which we used so the webjob functions would unexpectedly run.
```csharp
private static IConfigurationRoot BuildConfiguration()
{
    var configurationBuilder = new ConfigurationBuilder()
        .AddJsonFile("appsettings.json", optional: true);
    configurationBuilder.Sources.Add(new WebJobsEnvironmentVariablesConfigurationSource());
    return configurationBuilder.Build();
}
```
The workaround for this we have used is to created a class and pass its type to DisableAttribute and have this class read the configuration.

**Comment by brettsam** [comment]
This does seem wrong. The only place we use this is where we determine disabled attribute so it's a fairly targeted removal but it'll affect a lot of people if there are side effects. I'll look through it and see what the impact would be (if any).
