### ISSUE TITLE
No documentation about JobHostOptions

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-webjobs-sdk#1963]
Using the version 3.0.0, JobHostConfiguration has disapeared.

To configure the webjob, from what I can see, I can use IOptions<JobHostOptions>. I search on google:
https://www.google.ca/search?rlz=1C1CHBF_enCA784CA784&ei=5hnFW8u1Ja-3ggf3n6igDQ&q=c%23+core+%22JobHostOptions%22&oq=c%23+core+%22JobHostOptions%22&gs_l=psy-ab.3...5061.5741.0.6012.2.2.0.0.0.0.119.212.1j1.2.0....0...1c.1.64.psy-ab..0.0.0....0.7dbt4mv3PfE

There is no result.

Could you write a documentation explaining how to make a new JobHost using IOptions<JobHostOptions>

My final purpose is to be able to continue to use:

  ```
var jobHostConfiguration = new JobHostConfiguration();
            jobHostConfiguration.JobActivator = new JobActivator(host);
            jobHostConfiguration.Queues.MaxDequeueCount = 1;
            jobHostConfiguration.Queues.BatchSize = 1;
            jobHostConfiguration.Queues.MaxPollingInterval = TimeSpan.FromSeconds(15);
            jobHostConfiguration.DashboardConnectionString = ConnectionStringsSettings.AzureWebJobsDashboard;
            jobHostConfiguration.StorageConnectionString = ConnectionStringsSettings.AzureWebJobsStorage;
```

which stop working on v3.0.0 because JobHostConfiguration disapeared. 
- https://github.com/Azure/azure-webjobs-sdk/issues/1918
- https://github.com/Azure/azure-webjobs-sdk/issues/1903

I image that I can configure it in the appsettings using something like:

```
	"JobHost": {
		"DashboardConnectionString ": "xxxxxx",
		"StorageConnectionString ": "xxxxxx",
		"Queues": {
			"MaxDequeueCount ": "1",
			"BatchSize ": "1",
			"MaxPollingInterval ": 15
		}
	},
```

Thanks for your help.

**Comment by ranouf** [comment]
I read the example here:
https://github.com/Azure/azure-webjobs-sdk/tree/dev/sample/SampleHost

Line 23, I have this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IWebJobsBuilder' does not contain a definition for 'AddAzureStorage' and no accessible extension method 'AddAzureStorage' accepting a first argument of type 'IWebJobsBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by ranouf** [comment]
From what I can see here:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs/ the last version available is 3.0.0
But here, 11 days ago, a new version has been release:
https://github.com/Azure/azure-webjobs-sdk/releases

So from I could understand, this 2 solutions proposed in this issues
#1918
#1903
reference to version 3.0.1.

How can I have the version 3.0.1 to be able to configure my webjob as I did in the past?

**Comment by ranouf** [comment]
The solution is to use the package "_Microsoft.Azure.WebJobs.Extensions.Storage_" nuget package.

**Comment by ranouf** [comment]
But there is still no documentation available, so I let the issue opened :)

**Comment by ggailey777** [comment]
The PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/65322 addresses the SDK 3.x API updates, but it doesn't yet include examples of setting the binding properties. I am working on that now. Very sorry for the delay in getting the official documentation for WebJobs SDK updated.

**Comment by mathewc** [comment]
@ggailey777 has a couple PRs updating https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/app-service/webjobs-sdk-get-started.md and https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/app-service/webjobs-sdk-get-started.md for v3.x. Those updates should be published live soon.

From then on, the standard feedback links on the doc can be used to provide feedback on the doc, and issues for doc can be created in the docs repo: https://github.com/MicrosoftDocs/azure-docs/issues rather than this repo.

We'll wait for the doc to go live before closing this issue.

**Comment by mathewc** [comment]
New doc is now live:

- https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started
-  https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to

For any further issues,  use the feedback links on the doc, and issues for doc can be created in the docs repo: https://github.com/MicrosoftDocs/azure-docs/issues rather than this repo.
