### ISSUE TITLE
Give a better exception message when the name pattern has two keys with the same value

### ISSUE THREAD

**Issue by victorhurdugaci** [Azure/azure-webjobs-sdk#210]
```
public static void BlobTrigger([BlobTrigger("input/{name}/b/{name}.{ext}")] string blob)
```

Notice there are to "name" groups. Today we get an exception saying
```
{"Error indexing method 'BlobTrigger'"}
```
with an inner exception:
```
{"An item with the same key has already been added."}
```

We should perform an extra check and tell that a named group with the same name has already been added to parameter "blob"

**Comment by ryanhart2** [comment]
I get the same exception when using a class that inherits from a base class and hides one of the inherited properties with the ```new``` keyword. The exception message was not particularly helpful in diagnosing the problem, although that was in part due to my inexperience. If the duplicate key was named, this would have made things clearer e.g. "An item with the key 'ImageCount' has already been added."

```c#
public static void ProcessQueue([QueueTrigger("adverts")] AdvertMessage message) {...}

public class Advert {
   public int? ImageCount { get; set; }
}

public class AdvertMessage : Advert
{
  new public int ImageCount { get; set; }
}
```

**Comment by mathewc** [comment]
@ryanhart2 Thanks for reporting. I've improved the error message as you suggested in this commit: https://github.com/Azure/azure-webjobs-sdk/commit/84faf3260d4c023edb4f52de3fd721e72abe35eb. Message now looks like: "**Multiple properties named 'ImageCount' found in type 'AdvertMessage'.**" When replacing a property using 'new' and **changing the return type**, reflection will return both the base and derived properties. I'm going to leave this as an error (with a better message), since it's an odd corner case, and I don't want to mess with our serialization/contract logic to deal with it.

Regarding the original issue, it no longer repros for me.
