### ISSUE TITLE
Azure function not always triggered when an event is sent to event hub event stream

### ISSUE THREAD

**Issue by mguglani** [Azure/azure-webjobs-sdk#2220]
I have configured an event hub to export Activity Logs. I am using the following event hub trigger function to receive the events from event hub.
module.exports = function (context, eventHubMessages) {
    context.log(`JavaScript eventhub trigger function called for message array ${eventHubMessages}`);

    eventHubMessages.forEach((message, index) => {
        context.log(`Processed message ${message}`);
        context.log(`EnqueuedTimeUtc = ${context.bindingData.enqueuedTimeUtcArray[index]}`);
        context.log(`SequenceNumber = ${context.bindingData.sequenceNumberArray[index]}`);
        context.log(`Offset = ${context.bindingData.offsetArray[index]}`);
    });

    context.done();
};
To create an activity log I change the tags for the Resource group. Problem I am debugging is that I see the EventHubs stats incrementing when a new activity log is generated but I don't see the trigger function always being called. Is there any recommendation on how do I go about debugging this issue given that event hub does see the messages.

My bindings:

{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "eventHubMessages",
      "direction": "in",
      "eventHubName": "insights-operational-logs",
      "connection": "xxxxxx_RootManageSharedAccessKey_EVENTHUB",
      "cardinality": "many",
      "consumerGroup": "$Default"
    }
  ]
}
To Reproduce
Issue is not consistently reproducible but I hit the issue couple of times during half a day of testing yesterday.

 Moving the issue here based on inputs from ramya-rao-a:

https://github.com/Azure/azure-event-hubs-node/issues/214
=====================
@mguglani So to summarize

You have an Azure function written in Javascript that uses the Event Hub trigger such that for every message sent to Event Hubs, your function gets called
You see proof of incoming and outgoing messages for the Event Hub stats, but don't see your code being called
https://github.com/Azure/azure-webjobs-sdk/ is the reposiotry for the Event Hubs Triggers. Please log this issue there to get the right support.

This repository is for the @azure/event-hubs library which you would use in a nodejs app in order to interact with Event Hubs
=====================

**Comment by brettsam** [comment]
@mguglani -- were you ever able to figure out this issue? It may have been due to triggers being out-of-sync -- and we've recently released updates that will help. If you're still seeing it, please let me know and we can take a deeper look.

**Comment by secureaiexplorer** [comment]
@brettsam I have not recently tried it. Can you share the details of improvements that have been made?

**Comment by brettsam** [comment]
The main one I was thinking about is here -- https://github.com/Azure/azure-functions-host/pull/4070, and there were a lot of follow-up improvements. The ScaleController (the service that watches for events and "wakes up" your app when needed) would occasionally get out-of-sync with what it should be watching. That would mean that you'd need to explicitly start your app in order to process anything. The change above means we're always making sure that these triggers are in sync across both systems.

This was committed back in Feb (although there were a wave of newer improvements) so I'm not sure if it's what you were seeing.

If you're not still seeing this issue, I'm going to go ahead and close this. But please feel free to re-open if you see it again and we can get some more details from you.
