### ISSUE TITLE
ConfigureWebJobs adds appsettings.json, which can break configuration precedence

### ISSUE THREAD

**Issue by nathansoz** [Azure/azure-webjobs-sdk#2247]
#### Repro steps

In your net core 2 host builder do:

```
.ConfigureAppConfiguration(
                    (context, config) =>
                    {
                        config
                            .AddJsonFile("appsettings.json", false, true)
                            .AddJsonFile("appsettings.override.json", false, true)
```

Where settings in override should override the default appsettings.

Then call .ConfigureWebJobs(…)

#### Expected behavior

Settings in appsettings.override.json should override settings in appsettings.json (if there is overlap)

#### Actual behavior

appsettings.json gets added by ConfigureWebJobs(…) again, so it actually overrides ALL other configuration order set up previously in startup.

This breaks the principle of least surprise and can cause really subtle and maddening bugs.

**Comment by PlaidPhantom** [comment]
I believe I am running into this bug as well.  I have set up my project to have both an appsettings.json as well as user secrets.  My standard practice is to include my secret keys in appsettings.json as empty strings so that their existence is "documented" in the project (I do this often in web apps), and my secrets are not being seen unless i replace the empty string in appsettings.json.  If I don't reference that setting name in appsettings.json it references the user secrets as expected.

As a workaround, I am adding an underscore to the setting name in appsettings.json and everything appears to be working.

**Comment by brettsam** [comment]
Gonna close this as #1931 will cover this as well.
