### ISSUE TITLE
Add filter/search by Status to Function Invocation Log in Azure WebJobs dashboard

### ISSUE THREAD

**Issue by lesley-w** [Azure/azure-webjobs-sdk#2281]
At the moment it is impossible to find Failed jobs without paging through hundreds of successful jobs.

Add the ability for the user to just see a list of Failed jobs.

**Comment by paulbatum** [comment]
Thanks for the feature request, but we are no longer investing in the WebJobs dashboard. Most importantly, it does not work with WebJobs 3.x. We recommend monitoring WebJobs with App Insights:
https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started#add-application-insights-logging

I am closing this issue because we would only consider updating the dashboard for extremely critical issues impacting customers that have been unable to migrate to App Insights.
