### ISSUE TITLE
.NetCore 3.0 Upgrade

### ISSUE THREAD

**Issue by batizar** [Azure/azure-webjobs-sdk#2286]
Hi, I was just wondering if there is any plans for .NetCore 3.0 upgrade of the SDK.

Thanks.

**Comment by paulbatum** [comment]
Can you elaborate a little on what you had in mind? WebJobs targets .NET Standard 2.0. If we updated the SDK to take advantage of .NET Core 3.0 features, it would not longer be .NET Standard 2.0 compatible.

**Comment by batizar** [comment]
@paulbatum Yes, I wanted to know if there will be a .NET Standard 2.1 version of it available.

**Comment by paulbatum** [comment]
Providing a .NET Standard 2.1 version would require multi targeting, because we have no plans to drop .NET Framework support. We could do this, but only when we feel like we're getting something particularly valuable or important out of introducing that complexity. Did you have any specific ideas about why a .NET Standard 2.1 targeted version of WebJobs would be useful? For example is there some specific APIs surface that you're thinking of that should use `Span<T>`?

**Comment by batizar** [comment]
Nothing from top of my head right now but there seems to be some performance improvements from just upgrading the host .NetCore 3.0 so I was wondering if you guys have any plans to look into it.

**Comment by paulbatum** [comment]
Got it. Upgrading the functions host to .NET Core 3.0 is a different work item to what you described above and yes we are absolutely working on that. You can follow our progress here:
https://github.com/Azure/azure-functions-host/tree/3.x

There'll be more announcements and details on this as the work progresses.

I'm going to close this issue because we don't have any .NET Core 3.x upgrade plans for WebJobs SDK right now.
