### ISSUE TITLE
Which is better, one Azure Webjob and multiple triggers or multiple Azure Webjobs and one trigger?

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-webjobs-sdk#2306]
I m currently developing a solution where I need to use Azure Webjob. I have 4 QueueTriggers to handle, they all share some common code.

Usually I create an Azure WebJob per trigger and create a Common library.

But I realized that I could have only one Azure Webjob which manages all Triggers. The interesting part with that is there is only project and one HostBuilder is instanciated which means less ressources used on the webapp (I imagine). Of course this webjob won t be a singleton to be able to manage many threads for each trigger.

But there is maybe some side effect I dont know.

What do you suggest?

Thanks

**Comment by brettsam** [comment]
When you say --

> Usually I create an Azure WebJob per trigger and create a Common library.

-- do you mean you're creating separate *projects* for each trigger?

You can absolutely use many triggers in a single project. For most people, that's the approach we recommend. Like you said, there's less overhead this way (one project; one deployment; etc). For certain scenarios it can be better to run separately -- you may have one really resource-intensive function that you'd like to run separately because it makes things easier to monitor and tune.

**Comment by ranouf** [comment]
Yes, exactly, I created a separate project for each trigger.

Thanks for your answer which confirms my thinking :)
