### ISSUE TITLE
Long function app name cuts when we create a blob for singleton lock

### ISSUE THREAD

**Issue by alrod** [Azure/azure-webjobs-sdk#2363]
1. Create a function with name `getimpressionsschedulerfunctionapp-1m-prod-v2` and a time trigger with name `TimerTrigger1 ` in it.
2. Create a function with name `getimpressionsschedulerfunctionapp-10m-prod-v2`and a time trigger with name `TimerTrigger1 ` in it.
3. Point both function to the same storage account.
4. Both function use `azure-webjobs-hosts/locks/getimpressionsschedulerfunction/Host.Functions.TimerTrigger1.Listener`  as singleton blob.

Expected: 
The functions should use different singleton blobs.

**Comment by mathewc** [comment]
This isn't an SDK issue, it's a Functions issue due to the IHostIdProvider implementation that Functions uses, which truncates to 32 characters. See https://github.com/Azure/azure-functions-host/issues/2015. I think this is a dupe.

**Comment by v-anvari** [comment]
Hi @alrod, We hope your issue is resolved by taking reference from ["Azure/azure-functions-host/issues/2015".](https://github.com/Azure/azure-functions-host/issues/2015). We are closing this issue, since this is related to #2015. Please feel free to reopen this issue, in case of any further concerns.
