### ISSUE TITLE
Webjobs won't stop when deployed via WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by mattwoberts** [Azure/azure-webjobs-sdk#2389]
I'm deploying via azure pipelines. This uses a zip deploy, which in turn uses the new deployment method - `WEBSITE_RUN_FROM_PACKAGE`

My deployment includes some continuous webjobs, which are then started when the deployment completes. 

However, when you try to stop these webjobs, it doesn't work. I'm assuming this is because the wwwroot folder is locked, so stopping the webjob doesn't succeed.

I think this is related to https://github.com/Azure/azure-webjobs-sdk/issues/2324

#### Repro steps

Create an azure deployment pipeline that deploys webjobs.
Use the `AzureWebApp@1` pipeline task to deploy to azure (see screenshot)

![image](https://user-images.githubusercontent.com/109196/71106493-61194800-21b7-11ea-8a61-ed9ba8583463.png)

Deploy to azure app service, and see that the webjobs have deployed and are running.

Attempt to stop the webjob.

**Comment by jonarmstrong** [comment]
I have the same issue with all of the web jobs that I deploy using `WEBSITE_RUN_FROM_PACKAGE`. The desire is that I should be able to stop a WebJob without taking the entire site down.

**Comment by alohaninja** [comment]
@mattwoberts - your hunch is probably correct, run-from-package makes the entire site directory read-only. You can't disable the individual webjobs as it requires a file `disable.job` to be present in the webjobs directory for the job you wish to stop. 

## Option 1: Migrate to Functions
We are moving some of our infrastructure from webjobs to functions as this is likely a limitation with webjobs current infrastructure supporting the more modern deployment techniques. Azure Functions do allow you to disable individual functions even when using run-from-package - primarily because they [changed the disabled approach to using App Settings)](https://docs.microsoft.com/en-us/azure/azure-functions/disable-function) (_`AzureWebJobs.<FUNCTION_NAME>.Disabled`_) instead of files placed on the filesystem. 

## Option 2: Use Disable Attribute
If you aren't able to move your webjobs directly to functions - you can try the [`Disable` attribute](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs/DisableAttribute.cs) and leverage the same functions approach today by[ creating your own app setting to disable your individual webjobs](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to#disable-attribute). The extra work for adding an app settings disable flag seems to be done automatically for you in functions.

### Disabled Attribute for Webjobs
``` csharp
[Disable("Disable_QueueWebJob")]
public static void QueueWebJob([QueueTrigger("testqueue2")] string message)
{
    Console.WriteLine("Webjob with Disable attribute executed!");
}
```

### Setting the App Setting via Azure CLI
``` ruby
az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings Disable_QueueWebJob=1
```

**Comment by KZeronimo** [comment]
@alohaninja any recommendations for disabling continuous web jobs (NoAutomaticTrigger) that are invoked explicitly.  The disable flag approach doesn't seem to work from my testing

It seems continuous web jobs are a bit of a niche ...

**Comment by v-anvari** [comment]
Hi @KZeronimo , This seems like a different issue, we have raised a new issue for the same, which will be followed up in [#2583](https://github.com/Azure/azure-webjobs-sdk/issues/2583). Closing this issue.

**Comment by MDornian** [comment]
This is super frustrating as we have just spent a large number of resources developing a Webjob and now we can't stop or pause it when we need to without bringing down the whole website. This problem is almost 5 years old so I don't expect to ever see a real solution
