### ISSUE TITLE
Release beta versions on NuGet

### ISSUE THREAD

**Issue by toburger** [Azure/azure-webjobs-sdk#2481]
`Microsoft.Azure.WebJobs.Extensions.Storage` is available as version 4.0.0-preview1 on NuGet.
The rest of the packages should also be made available as preview packages.

Rationale: `Microsoft.Azure.WebJobs.Host.Storage` 3.0.14 is still referencing `WindowsAzure.Storage` which can/should be considered deprecated.

**Comment by onionhammer** [comment]
Seems like a half-hearted attempt at deprecating packages if there's 2 different deprecated windowsazure storage nuget package suites still in active use by microsoft...

- WindowsAzure.Storage [Deprecated] but still in use
- Microsoft.Azure.Storage.* [Deprecated] but still in use
- Azure.Storage.* The new hotness

^ Confusing mess, and most large projects are probably using all 3 suites of packages because of deeply nested dependencies

**Comment by v-anvari** [comment]
Hi @toburger , There is a beta  package available here
[Microsoft.Azure.WebJobs.Extensions.Storage/5.0.0-beta.1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/5.0.0-beta.1).

You can also find the related discussion in [#2575](https://github.com/Azure/azure-webjobs-sdk/issues/2575)
