### ISSUE TITLE
Unhandled Exception: System.TimeoutException: The operation 'GetMessageAsync' with id '' did not complete in '00:03:00'.

### ISSUE THREAD

**Issue by jhested** [Azure/azure-webjobs-sdk#2506]
We are experiencing constant timeout issues when using Azure Webjobs, which causes the WebJob to shutdown and restart around 10 times every day.

This has been ongoing for a year or so, and we have tried various ways to get around it, including 
ServicePointManager.DefaultConnectionLimit = 500;
and increasing threadpools by using this [code](https://github.com/Azure/azure-functions-host/blob/43a4b641cdda19a3291fa3b61df50d5f801791ca/src/WebJobs.Script.WebHost/Global.asax.cs#L50)
ThreadPool.SetMinThreads(minThreadCount, minThreadCount);

We mostly use QueueTriggers with a mix of async and non async functions. We have a total of around 30 queues.

I have also tried to see if theres correlation with active thread count when the exception occurs, but theres anything between 50-110 active threads when the exception occurs so it doesn't seem to be related.

Some also suggests moving to Azure Cosmos DB, but im not exactly sure how to migrate.

https://stackoverflow.com/questions/60397419/webjob-queuetrigger-timeoutexception-the-operation-getmessages-did-not-comple
https://github.com/Azure/azure-webjobs-sdk/issues/1393
https://github.com/Azure/azure-webjobs-sdk/issues/755

At the moment we are not sure how to get around this issue, so any advice on how to approach this would be much appreciated

#### Related information 

I have attached our packages.config as well as log output.

Please let me know if you need any further information
[packages.config.txt](https://github.com/Azure/azure-webjobs-sdk/files/4722486/packages.config.txt)
[webjob_log.txt](https://github.com/Azure/azure-webjobs-sdk/files/4722488/webjob_log.txt)

**Comment by brettsam** [comment]
Can you give the WebJobs Storage Extension 4.0.1 a try?

**Comment by jhested** [comment]
I've had the job running with version 4.0.1 since 21:09 UTC last night, but unfortunately it made no difference.

I've attached the latest log file
[jobs_log.txt](https://github.com/Azure/azure-webjobs-sdk/files/4727702/jobs_log.txt)

**Comment by brettsam** [comment]
Note that (if it's the issue that's been plaguing us for months) -- there's a deadlock when parsing XML responses and the response hangs forever. In order to break the deadlock, we have to restart the process.

We've been working with the Storage SDK team on a solution -- the current release 4.0.1 was supposed to have all the scenarios covered, but I'm going to put out a 4.0.2 release soon that pulls their latest nuget package. In the meantime you can try directly referencing Microsoft.Azure.Storage.Queue 11.1.7 -- they've been making a bunch of networking improvements recently: https://github.com/Azure/azure-storage-net/blob/master/Queue/Changelog.txt

If that doesn't help, I suspect that something else may be affecting you here. With 30 functions (and some synchronous) you may be hitting other kinds of deadlocks and/or thread starvation. If it's fairly easy to hit these -- are you able to disable some of your "heavier" functions -- or move them to a separate WebJob project? Or go async everywhere and see if that helps? Can you tell if any particular function is always running when this happens?

**Comment by jhested** [comment]
Thank you very much for your feedback.

I have now been able to reproduce the issue in a test project i created, by using the following approach.

1. Create 30 functions with queuetriggers
2. In each function, spawn 5 tasks that calls a test website with a build-in Task.Delay(5 min) and wait for result.(Also increasing default WebRequest.Timeout to 6 min. (I guess anything > 3 mins would work)
3. Put 500 messages in each queue

This cause the webjob to throw the timeout exception within 5 minutes. And i reproduced the issue 5 times in 1 hour.

(This might be an obvious reason for the exception to occur, but I wasn't sure if it would cause this behavior or not)

After being able to reproduce the issue reliably, I changed all functions to async and implemented async/await where appropriate( await WebRequest.GetResponseAsync(), etc).
The webjob has been running for some hours now without any exceptions.


As you mention, I was expecting it to be related to deadlocks on resources, but it's an effort that we rather only do when we confirm that is the cause. We are requesting a lot of external resources via http in the various jobs, and i know that some of the external requests sometimes times out.

Based on your comments and above results from the testproject, I think the plan for us from here is to slowly migrate all functions to a new project, where they will then be implemented with the async pattern.

**Comment by brettsam** [comment]
Thanks for the dilligence here, @jhested. Since there's nothing on our end to be fixed, I'm going to close this issue.

For anyone else running into this -- take a look at your resource utilization and async patterns. This exception acts like a "warning" that something isn't able to complete (thread starvation; network contention, etc). We'll be removing the exception itself in a future release but that won't fix any underlying issues with the health of the app.
