### ISSUE TITLE
Upgrade of Microsoft.Azure.WebJobs.Extensions.Storage to 4.0.2 fails.

### ISSUE THREAD

**Issue by chitoiur** [Azure/azure-webjobs-sdk#2520]
Please provide a succinct description of the issue.

We are trying to upgrade Microsoft.Azure.WebJobs.Extensions.Storage from v3 to v4 and are unable to do so because of the following error from Nuget:

Version conflict detected for Microsoft.Spatial. Install/reference Microsoft.Spatial 7.5.3 directly to project BeneLynk.DocumentComposition to resolve this issue. 
 Our Project -> Another Project Dependency -> Microsoft.Azure.Search 10.1.0 -> Microsoft.Azure.Search.Service 10.1.0 -> Microsoft.Spatial (>= 7.5.3) 
 OurProject -> Microsoft.Azure.WebJobs.Extensions.Storage 4.0.2 -> Microsoft.Azure.Cosmos.Table 1.0.7 -> Microsoft.OData.Core 7.5.0 -> Microsoft.Spatial (= 7.5.0).	BeneLynk.DocumentComposition

The problem seems to be the hard dependency of Microsoft.OData.Core on Microsoft.Spatial version 7.5.0. Not sure why it's = and not >=. One solution is to install Microsoft.Spatial directly, but that breaks other things and we should have to do that in the first place. Any ideas?

**Comment by myfinder** [comment]
I have this problem too.

**Comment by VienArchway** [comment]
Update nuget version of Spatial and OData.Core to latest version. That's solved my problem.

```
<PackageReference Include="Microsoft.Spatial" Version="7.7.1" />
<PackageReference Include="Microsoft.OData.Core" Version="7.7.1" />
```

**Comment by ThejaChoudary** [comment]
@chitoiur **Microsoft.Azure.Search** package has been deprecated as it is legacy and no longer maintained. Can you please use alternative **Azure.Search.Documents** .
And also please make use of  the latest versions to avoid version conflicts.
 **Microsoft.Azure.WebJobs.Extensions.Storage**  4.0.3
**Microsoft.Azure.Cosmos.Table**  1.0.8
**Microsoft.OData.Core**  7.7.3
**Microsoft.Spatial**  7.7.3

Please let is know if you still face the issue so that we can investigate more
Thank You
