### ISSUE TITLE
Consider supporting wildcard parameter name in DataBindingProvider

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-webjobs-sdk#2729]
Currently, [DataBindingProvider ](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/Data/DataBindingProvider.cs#L24) matches on the parameter name specified in the bindingDataContract dictionary. There are times when this is not necessary as there would only ever be a single instance of the type that corresponds to the parameter. For example, we allow binding to the [ServiceBusMessageAction](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Triggers/ServiceBusTriggerBindingStrategy.cs#L60) type in the new Service Bus extensions. It shoudn't really matter here what the user uses as the parameter name. It would be great if an element could be added to the Dictionary with an "*" for the key to indicate that any name is acceptable. The side effect of this change would be users could define multiple parameters binding to the same instance, this could either be allowed or cause an exception depending on what is idiomatic for the framework.

It is possible to get the desired behavior without this, but it is more cumbersome, as I don't believe you would be able to use a BindingStrategy and instead would have to implement an IBinding yourself.

**Comment by JoshLove-msft** [comment]
Would be happy to contribute this if this it is something that would be accepted.
 
/cc @fabiocav @paulbatum

**Comment by JoshLove-msft** [comment]
A customer ran into this while trying out the new ServiceBus trigger - https://stackoverflow.com/questions/68350196/how-to-manually-handle-message-completion-in-c-sharp-azure-function-with-azure-s

**Comment by mathewc** [comment]
Thanks for logging the issue @JoshLove-msft. Yes the fact that data contract bindings for non-trigger parameters must match the static contract name is something that confuses users. From the beginning of the WebJobs SDK this is how it's behaved.

The fact that the binding contract is a dictionary means I don't think that putting a asterisk value for some of the contract members will work, since your binding may have several values of this type that it wants to support. For example in the ServiceBus trigger contract [here](https://github.com/Azure/azure-sdk-for-net/blob/70896b8ea1ca4007c381ea2ffeb4be9d84adfa7a/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Triggers/ServiceBusTriggerBindingStrategy.cs#L94) you'd likely want to allow any parameter name for binding to both ServiceBusSessionMessageActions and ServiceBusMessageActions? The dictionary can't have duplicate asterisk values to support this.

Instead, as you've suggested, we might also address the issue by providing a better error message. The code [here](https://github.com/Azure/azure-webjobs-sdk/blob/4a16c273b40ee47ec318bb6d7aa12e0075f30402/src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs#L257) that logs the binding error has access to the binding contract, so could also log the available bindings based on the parameter type. I.e. if we see that the contract does contain the parameter type, we could instead emit an error message like:

**Microsoft.Azure.WebJobs.Host: Error indexing method 'SBQ_F1_VC'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'msgActions' to type ServiceBusMessageActions. The binding supports the following parameter names for type ServiceBusMessageActions: ("messageReceiver", "messageActions"). Try renaming your parameter to one of those values.**

An approach like this would be safe (wouldn't violate long standing contract behaviors/assumptions) and would allow customers to quickly see and fix the issue. I think we should start by just improving the error output here.

**Comment by JoshLove-msft** [comment]
Fair point that an extension may need multiple such parameters, so the asterisk alone wouldn't work. 

I think improving the error message would probably get us most of the way there as users can quickly fix the issue themselves without needing to read docs.

**Comment by fabiocav** [comment]
@mathewc I'll move this to 107, but please let me know if we need to change and/or reassign

**Comment by mathewc** [comment]
@JoshLove-msft - PR https://github.com/Azure/azure-webjobs-sdk/pull/2756 improves the error message here as we discussed.
