### ISSUE TITLE
debug the az function run time code that receives the msg from service bus and deserializes

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-webjobs-sdk#2757]
Binding to poco object in servicebus topic trigger auto fills up datetime properties with datetime.min value if input json is string.empty.

#### Repro steps

Provide the steps required to reproduce the problem
1. create new Customer class with just OrderTimestamp property
2. create topic/subscription and one azfunction topic trigger
3.  post a json to topic with empty OrderTimeStamp property {"orderTimestamp" :""}
4.  inspect value in trigger function and u will see it filled with datetime.min value 1/1/001

Same thing fails if we receive msg as Message object in az function and then deserialze using newtonsoft json. It throws error.

#### Expected behavior
Actually i want to debug the az function run time code that receives the msg from service bus and deserializes it into the poco. I want to see how its deserializing it and what library its using for same.
Can someone provide guidance on how can i can do that. I tried looking into the call stack but i was not able to reach the correct place.

* Package version
```
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />
```
* Links to source

**Comment by v-bbalaiagar** [comment]
Hi @krishnasingh1818, We would like to have the piece of code that you are using in order to repro the project and error that you are seeing.
Meanwhile, Can you please go through the below links -
https://github.com/Azure/azure-webjobs-sdk/blob/dev/sample/SampleHost/Functions.cs
https://github.com/Azure/azure-functions-host/blob/dev/sample/CSharp/HttpTrigger-Poco/run.csx

Please check and let us know if this helps.
