### ISSUE TITLE
[AutoResolve] not working as expected

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-webjobs-sdk#2920]
I’m having a hard time reconciling various sources to create a custom Azure Function App binding.

I find examples that bind an attribute and its values to an input argument type using `BindToInput()`.
I also find examples that use an `IBindingProvider`-implementation using `Bind()`.

However, I cannot find samples that use both an `IBindingProvider`-implementation while still making use of an attribute.
Specifically, I need my custom binding to access values specified at the attribute level.

#### Repro steps

I have [uploaded a sample custom binding](https://github.com/springcomp/Extensions.Functions) with:

- A custom attribute with an `[AutoResolve]` decorated property.

```c#
[Binding]
[AttributeUsage(AttributeTargets.Parameter)]
public class AuthorizeAttribute : Attribute
{
    /// <summary>
    /// Initialize a new instance of the <see cref="AuthorizeAttribute" /> class.
    /// </summary>
    /// <param name="applications"></param>
    public AuthorizeAttribute(string applications)
    {
        Applications = applications;
    }

    /// <summary>
    /// The comma-separated list of allowed application identifiers (client-ids).
    /// May contain binding parameters.
    /// </summary>
    [AutoResolve]
    public string Applications { get; private set; }
}
```

- My config provider uses the following code to try and retrieve the attribute:

```c#
/// <summary>
/// Creates the <see cref="ClaimsPrincipalBinding" /> class.
/// </summary>
/// <param name="context"></param>
public Task<IBinding> TryCreateAsync(BindingProviderContext context)
{
    var parameter = context.Parameter;
    var attribute = parameter.GetCustomAttribute<AuthorizeAttribute>(inherit: false);

    IBinding binding = new ClaimsPrincipalBinding(attribute, logger_);
    return Task.FromResult(binding);
}
```

When using this custom binding, the `attribute` variable is initialized with the value specified from the function’s code.
For instance, instead of resolving the configuration value from app settings, the binding receives values such as `%MyConfiguration%` including the percent-characters.

#### Expected behavior

I would expect the `attribute` variable to receive the value referred to by the configuration parameter from app settings.

#### Actual behavior

The `attribute` variable is initialized with the value specified in the source code verbatim, including %-characters.

#### Summary

Is there any reliable sample that illustrates this problem?
How can I make sure `[AutoResolve]` works and resolve configuration parameters from app settings.

**Comment by ramya894** [comment]
@springcomp Please check the below link for creation of an attribute to provide the input for autoresolve.
https://microsoft.github.io/AzureTipsAndTricks/blog/tip247.html

Please comment below if you still need any help further.

**Comment by springcomp** [comment]
@ramya894 thanks for the feedback.

Indeed I followed tip 247 – however this tip specifically uses `BindToInput()` which I cannot use in my case.
I’m specifically interested in samples that use `Bind()` with an `IBindingProvider` implementation **and** take advantage of informations specified on the attribute level.

**Comment by ramya894** [comment]
@fabiocav/ @mathewc Kindly have a look into the above issue.

**Comment by mathewc** [comment]
When implementing the binding yourself by providing your own IBindingProvider, AutoResolve won't work. Instead, you must use INameResolver to manually resolve the attribute value. An example can be found [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/f60ddaa9da1065fca896a1ef98ab62dd46ffd97d/src/WebJobs.Extensions/Extensions/Timers/Scheduling/TimerSchedule.cs#L67). So you'd update your config provider to take the INameResolver from DI and flow it down into your binding provider (example [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/a0fb2011acfa88126d9eecc285d7a7f8283ccbe5/src/WebJobs.Extensions/Extensions/Timers/Config/TimersExtensionConfigProvider.cs#L23)), and call ResolveInWholeString yourself.

AutoResolve works only if you're using the BindToInput method, as you've found. That method auto creates the binding for you rather than you implementing an IBindingProvider, and that auto binding passes the attribute through an AttributeCloner which is the component that honors [AutoResolve](https://github.com/Azure/azure-webjobs-sdk/blob/3f4ec78be9f43bb041937425ced00b341883aa42/src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs#L140).

**Comment by springcomp** [comment]
@mathewc thanks a lot.

That is awesome and informative feedback and looks like exactly what I was looking for.
Will let you know if I need more help.
