### ISSUE TITLE
when using Microsoft.Azure.WebJobs.Extensions.ServiceBus >= 5.13.0 exception is thrown in startup of functionapp

### ISSUE THREAD

**Issue by ulluoink** [Azure/azure-webjobs-sdk#3050]
Please provide a succinct description of the issue.

after update of Microsoft.Azure.WebJobs.Extensions.ServiceBus from 5.12.0 to any version >= 5.13.0 an exception dutring startup of funtionapp occurs:
Microsoft.Azure.WebJobs.Extensions.Rpc: Method 'GetChangeToken' in type 'Microsoft.Azure.WebJobs.Extensions.Rpc.ExtensionEndpointDataSource' from assembly 'Microsoft.Azure.WebJobs.Extensions.Rpc, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. Value cannot be null. (Parameter 'provider')

we regsiter a servicebus client in startup by using AddServiceBusClient extension method from Microsoft.Extensions.Azure.ServiceBusClientBuilderExtensions

Provide the steps required to reproduce the problem

see above

#### Expected behavior

no exception 

#### Actual behavior

Exception is thrown:
Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.WebJobs.Extensions.Rpc: Method 'GetChangeToken' in type 'Microsoft.Azure.WebJobs.Extensions.Rpc.ExtensionEndpointDataSource' from assembly 'Microsoft.Azure.WebJobs.Extensions.Rpc, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. Value cannot be null. (Parameter 'provider')

#### Known workarounds

use version 5.12.0 of Microsoft.Azure.WebJobs.Extensions.ServiceBus

#### Related information 

Provide any related information 

* >= 5.13.0
* Links to source

**Comment by bhagyshricompany** [comment]
Thanks for reporting .pls provide the repro steps  and function invocation id,name,timestamp region etc.

**Comment by ulluoink** [comment]
it happens locally we have not deployed it.

exception occurs when calling the function endpoint

**Comment by bhagyshricompany** [comment]
pls share the all repro steps

**Comment by ulluoink** [comment]
What do you mean with "share all repro steps" I did that in the very beginning.

What else do You need to know?

**Comment by bhagyshricompany** [comment]
you getting issue  while adding and migrationg ?pls raise the issue on azure portal support.

**Comment by nask08** [comment]
Any update on this issue? We are facing the same when upgraded our Azure Function with Microsoft.Azure.WebJobs.Extensions.ServiceBus version 5.16.4 and framework to .NET 8.

**Comment by evandixon** [comment]
I recently encountered this issue, without having made any changes that seem relevant, and in my case I fixed it by removing `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` from the project file, added years prior because of different assembly-related issues. I guess they eventually fixed that issue.

Curious if anyone else in the thread had that in the project file. It'd make me more confident that this is actually the correct fix.

[Edit]
After further testing, I've found I still need _FunctionsSkipCleanOutput to avoid other assembly errors. My conclusion is that in-process Azure Functions for .Net 8 is just broken.
