### ISSUE TITLE
IEnumerable<> blob binding

### ISSUE THREAD

**Issue by victorhurdugaci** [Azure/azure-webjobs-sdk#35]
I would be really cool to have support for IEnumerable\<> binding on blob. 
The scenario where we need this is the PhluffyShffy sample: there is a container with the images uploaded by the user. When a queue message is picked up  by the job, it also needs get all the blobs associated to that message - the association is done by the name convention.

It would be something like:

```C#
[Blob("container/{fileName}")]IEnumerable<CloudBlockBlob> files
```

IEnumerable works well for CloudBlockBlob because you can get the blob name. For types which don't have this information, IDictionary\<string, T> might do the trick

```C#
[Blob("container/{fileName}")]IDictionary<string, Stream> files
```

**Comment by rustd** [comment]
From YJ:
1. User posts an article with multiple images. images are stored as blobs and the list of blobnames are queued for optimization webjobs process, let say queued POCO ArticleInfo has List<string> BlobNames property.
2. The optimization does some image manipulation jobs and generates 2 images each.

3. For that, WebJobs QueueTrigger gives ArticleInfo object, but you know WebJobs attribute cannot bind IList property in POCO.

```C#
public static void ProcessBlob([QueueTrigger("optimization")] ArticleInfo info, [Blob("image/{BlobNames}")] out IList<Stream> blobs) { ... } // cannot bind such type of property.

```

So, I'd like to propose container binding attribute for multiple blobs uploading as below.
```C#

public static void ProcessBlob([QueueTrigger("optimization")] ArticleInfo info, [Container("image")] out CloudBlobContainer container) { ... }
```

**Comment by YoungjaeKim** [comment]
thanks to add in the backlog. 'YJ' is me.

**Comment by mathewc** [comment]
This issue is now addressed by commit https://github.com/Azure/azure-webjobs-sdk/commit/91704de376cba81b175069ff766dcb20c822e6b8.

In summary, the new bindings now supported are:
* `[Blob("mycontainer")] CloudBlobContainer container`
* `[Blob("mycontainer")] IEnumerable<CloudBlockBlob> blobs`
* `[Blob("mycontainer/prefix")] IEnumerable<CloudBlockBlob> blobs`
  * returns all blobs in the container starting with "prefix"
* `[Blob("{Container}/{Prefix}")] IEnumerable<CloudBlockBlob> blobs`
  * model binding to Container/Prefix properties coming from e.g. a queue POCO message
* The `IEnumerable<T>` above can have a T of the following types:
  * ICloudBlob
  * CloudBlockBlob
  * CloudPageBlob
  * Stream
  * TextReader
  * String

See the [tests](https://github.com/Azure/azure-webjobs-sdk/blob/master/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/BlobBindingEndToEndTests.cs#L131) here for more binding examples.

**Comment by YoungjaeKim** [comment]
:+1:

**Comment by mathewc** [comment]
FYI: A build with this binding is now up on the [myget feed here](https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs).

**Comment by alexgman** [comment]
Is this addressing ONLY input bindings or ienumerable is supported for OUTPUT bindings to blobs?
