### ISSUE TITLE
Customer: Improve integration for custom code with continuous jobs

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#498]
The following suggestion bug was opened on the forums . This issue has lots of details so I encourage you to read through it.
What would be helpful is an event or some means for me to hook into the job host pipeline so that I can intercept stages in the pipeline and inject my own functionality, e.g. On starting, on started, on stopping, on stopped etc.
https://social.msdn.microsoft.com/Forums/en-US/e5031ea2-db11-470a-a1cd-304e7ee43fe5/webjobs-improve-integration-for-custom-code-with-continuous-jobs?forum=windowsazurewebsitespreview

**Comment by rustd** [comment]
some way of hooking in the SDK pipeline before/ after a function is executed so he can do something custom eg. send email etc

**Comment by mathewc** [comment]
I just reviewed the original stack overflow post - the customer is trying to use the SDK when I don’t think he even should be. He’s got worker role code that does its own queue listening code, so he can’t use the SDK to do this. He’s trying to somehow shove his existing entry point into JobHost – which is why he was asking for OnStart etc. However, he shouldn’t be doing this at all. Since he doesn’t need to use the SDK, he should simply be using WebJobs core – i.e., set up a continuous job and move his worker role code into a simple exe. He can use WebJobs "graceful shutdown" to run his cleanup code, etc.
