### ISSUE TITLE
Consider having `ExtensionRegistry` as first class property on `JobHostConfiguration`

### ISSUE THREAD

**Issue by amitapl** [Azure/azure-webjobs-sdk#512]
The following code snippet will be common for WebJobs SDK extensions:
```
    IExtensionRegistry extensions = config.GetService<IExtensionRegistry>();
    extensions.RegisterExtension<IExtensionConfigProvider>(extensionConfig);
```

My suggestion is to change it to:
```
    config.ExtensionRegistry.RegisterExtension<IExtensionConfigProvider>(extensionConfig);
```

Which is easier to discover.

**Comment by mathewc** [comment]
JobHostConfiguration is a hub that virtually all SDK users will use often, whereas comparatively the number of people that will author extensions will be relatively low. Authoring an extension is an advanced scenario, not mainline, and extension authors will have to know quite a bit to author one. So requiring them to fish out the registry from the service container doesn't seem that bad. David had also suggested that we might even create a VS extension template which would scaffold some things for people. Otherwise, they'll likely just be copying some examples we publish. Either way, it's not something they'll be coding by discovery, I think. Thoughts?

**Comment by amitapl** [comment]
Just because not many will use it doesn't mean we should make it harder, are we trying to hide it for a reason?
I think we should make writing an extension as easy as we can.

**Comment by mathewc** [comment]
Yes I agree that we want extensions to be as easy to write as possible. We'll need to balance that with keeping the mainline interfaces clean. Note there will be other system services in the container that won't necessarily have corresponding properties.

Anyhow, let's leave this open and think on it more :)

**Comment by mathewc** [comment]
Extension methods facilitating this are now part of the Microsoft.Azure.WebJobs.Extensions nuget package, which contains helper types/framework for extension authors. See: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions/Framework/JobHostConfigurationExtensions.cs
