### ISSUE TITLE
Extensibility for new and existing triggers and binders.

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#522]
This captures high level scenarios that should be possible when we open the extensibility for the SDK.

# Extensibility for New Triggers and Binders
* I can use/write a file watcher trigger
* I can use/write a timer to run my function on a schedule
*  I can write the dictionary cloud table binder
*  I can write a POCO blob binder
* I can write a SQL Azure trigger and/or binding
* I can describe a function as a singleton (within a scope) so that I can prevent concurrent execution
*  I can write a function that operates atomically on a blob (i.e. blob lease) 
		○ I can create my job class using a DI container
			§ Includes instance method support
			§ For DI consider using Project K’s pattern (or even implementation)
*  I can write jobs that use multiple Azure accounts
			§ Related: I can write jobs that use multiple Service Bus namespaces

# Extensibility for Existing Triggers, Binders, Polling
* I can write a custom queue polling algorithm

**Comment by mathewc** [comment]
Closing this, because all the items are already addressed, or already have separate tracking items for them. Specifically:

* FileWatcher/Timer extensions are already written using the new extensibility model
* "dictionary table binder" is tracked by issue #517 (extensibility allowing people to write these)
* POCO blob binder is already supported by ICloudBlobStreamBinder<T> support
* Singleton support is tracked by #513
* "multiple azure accounts" is tracked by #395
