### ISSUE TITLE
Triggers executed on unsuccessful write operations

### ISSUE THREAD

**Issue by martinknafve** [Azure/azure-webjobs-sdk#553]
The method IsBlobWrite in Microsoft.Azure.WebJobs.Host.Blobs.Listeners.StorageAnalyticsLogEntry returns true if a log entry in the analytic logs refers to a blob write operation. This implementation does not seem to take the HTTP status code found in the log entry into consideration, meaning that even unsuccessful operations will cause triggering. The documentation for Azure Storage Logs analytics mentions that not only successful operations are logged.

Is this the intended behavior? Should triggers be executed even if operations are not succesful?

**Comment by smartnose** [comment]
I have a similar question here: does WebJobs imposes any sort of ordering of output operations?

For example, I have a function:

public static void SampleFunction(
        [ServiceBusTrigger(Topic1, Subscription1) triggeringMessage,
        [Blob("output_blobs/{blobName}")] out blobContent,
        [ServiceBus(Topic2)] out string downstreamMessage);

Can I enforce that the output message is only sent to Topic2 AFTER blobContent is uploaded?

**Comment by mathewc** [comment]
Are you logging this bug because you're actually seeing that we call your function for failed updates? We have code later in the pipeline that should be detecting whether a successful write actually occurred, based on ETag (code [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/BlobTriggerExecutor.cs#L59)).

I expect that there isn't actually an issue here - please confirm.

**Comment by mathewc** [comment]
Closing this since we haven't heard back.
