### ISSUE TITLE
Move to the latest major versions of Azure Storage and Service Bus SDKs (and other dependencies)

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#565]

**Comment by mathewc** [comment]
Note, for the v1.1.0, we've already moved forward to all the latest versions for the major version trains we're on.

**Comment by mathewc** [comment]
Update - we've tested wtth Azure Storage version 5.0.2 and we now allow that. However, until our 2.0 release, we won't be able to move to all the latest versions.

**Comment by mteper** [comment]
@mathewc: Is there a roadmap / timeline for 2.0 release?

**Comment by mathewc** [comment]
Not dates yet.

**Comment by Crypth** [comment]
That is a bit weird. Last version (1.1.0) used Storage 6.2.0 according to my packages.config. The NEW version 1.1.1 downgraded the windows azure storage to 5.0.2. I haven't manually fiddled around with this and the web jobs have been running fine. Any idea whats going on?

**Comment by mathewc** [comment]
Yes, see this issue for all the details https://github.com/Azure/azure-webjobs-sdk/issues/596. Basically there was a binary compat issue introduced in storage 6.1 and we were having lots of customers upgrade to that and the SDK was failing because of the breaking change. So we put a cap on the supported range - allowing up to what we know works. That was all before 6.2 was released, which fixed the issue. So in our latest alpha prerelease versions, we've extended the version range to 6.2.

**Comment by davidebbo** [comment]
If 6.2 works fine, it's better not to set it as an upper bound, but simply leave it unbounded. Bounding things tends to cause more problems than it solves in the NuGet world. e.g. if they release a 6.2.1, you'll have to keep adapting your upper bound.

**Comment by mathewc** [comment]
Perhaps - we only introduced the bounding because breaking changes were introduced, and we wanted to prevent incompatible updates that broke people. Now that those have been fixed, upgrades will just work again for the time being. While the possibility exists for them to release another incompatible version before we release our 2.0, perhaps that chance is small.

**Comment by Crypth** [comment]
I understand the predicament. I was just baffled by the downgrade and wanted to make sure nothing is wrong with the package. As it works fine either way for us we'll just keep using the one set by the webjobs package. Thanks for clarifying!

**Comment by davidebbo** [comment]
My old post http://blog.davidebbo.com/2011/01/nuget-versioning-part-2-core-algorithm.html covers this well. See the "When an upper bound makes sense" section.

**Comment by Zoltu** [comment]
> So in our latest alpha prerelease versions, we've extended the version range to 6.2.

When will the alpha show up in NuGet?  At the moment, I only see 1.1.1 as the latest and before that the most recent release was November.

**Comment by fwd079** [comment]
@mathewc thank you very much for [this tip](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds) to use nightly build. :+1:  :)

I am using a class library for queue and blob operations with latest Storage API, this build fixes my warnings for "conflicting versions" during builds.

**Comment by sandorfr** [comment]
This would be the first step in order to enable .net core support. I would love to see this move forward :)

**Comment by fwd079** [comment]
Storage 7 is here, this is still stuck in alpha I think. Is Microsoft planning to ditch this SDK?

**Comment by mathewc** [comment]
Guys, we've just released version **1.1.2** of the SDK on Nuget.org. This version is a hotfix to 1.1.1 that removes the Storage version cap that we had in place. So if you upgrade to 1.1.2 you should now be unblocked to upgrade to later storage versions. You should be fine upgrading to 6.2 - I did a test pass on that and it looked good. I haven't tried 7.0 yet.

As detailed above in this issue, we haven't moved the SDK to these later versions, because we haven't ourselves revved our major version. We expect to release a 2.0 hopefully later this year that moves the SDK to all the latest across our dependencies.

**Comment by mathewc** [comment]
@fwd079 Of course we're not planning on ditching this SDK. On the contrary, it has become the foundation for a bunch of new critical work we're doing for [Azure Functions](https://azure.microsoft.com/en-us/services/functions/) so we're very much invested in it.

**Comment by mteper** [comment]
Anyone tried with 7.0 yet? Any issues?

**Comment by mathewc** [comment]
Some reports of using 7.0 successfully [here](https://github.com/Azure/azure-webjobs-sdk/issues/631)

**Comment by mathewc** [comment]
Commit https://github.com/Azure/azure-webjobs-sdk/pull/709 has moved the SDK to the latest packages of all our main dependencies.
