### ISSUE TITLE
Create and manage app.config transformations

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#587]
Copied from https://github.com/Azure/azure-webjobs-sdk-samples/issues/5

In a complex web application, WebJobs have the potential to be deployed in many different "environments" inside Azure. At AdvancedREI, we have 3 environments for beta, staging, and production. Since WebJobs are console apps, there is not built-in support for app.config transformations. I tried downloading a 3rd-party VSIX on the Visual Studio Gallery that is supposed to enable this, but Publishing from Visual Studio does pick up the transformed file.

It would be easier if the SDK would just allow this to happen automatically, either through improved compatibility with [the 3rd-party VSIX](https://visualstudiogallery.msdn.microsoft.com/579d3a78-3bdd-497c-bc21-aa6e6abbc859), or through end-to-end added support.

**Comment by mathewc** [comment]
Thanks. We'll discuss this on the team and figure out the right course of action. I see the issue has been languishing, probably because the original issue was logged in the samples repo.

**Comment by abatishchev** [comment]
Thanks a bunch!

In my scenario, the web project is being built and published, its web.config is transformed but app.config in the referenced by json config console project is not.

**Comment by davidebbo** [comment]
I don't think this is related to the WebJobs SDK, but is a general VS WebJobs publishing issue regardless of the use of the SDK. i.e. you'd have the same issue with a trivia WebJobs console app.

@bradygaster may have more to say about this (and had in fact commented earlier in the other thread).

There may be a better place to discuss as it is not actionable in this code base.

**Comment by mathewc** [comment]
This is a VS tooling issue, and we've looped in the VS team and they've opened an **internal** tracking item for this. There is also a **public** VS User Voice issue (link here) that has lots of traction. Since this issue isn't actionable in the SDK, I'm closing the issues in these repos. All further comments should go to the VS user voice issue and to the VS team.

**Comment by RonakThakkar** [comment]
Hi,

I had same requirement in my project. I tried slowcheetah plugin that does
app.config transformation for console applications.

Regards
Ronak Thakkar

On Oct 27, 2015 8:43 AM, "Alexander Batishchev" <notifications@github.com>
wrote:
>
> Copied from Azure/azure-webjobs-sdk-samples#5
>
> In a complex web application, WebJobs have the potential to be deployed
in many different "environments" inside Azure. At AdvancedREI, we have 3
environments for beta, staging, and production. Since WebJobs are console
apps, there is not built-in support for app.config transformations. I tried
downloading a 3rd-party VSIX on the Visual Studio Gallery that is supposed
to enable this, but Publishing from Visual Studio does pick up the
transformed file.
>
> It would be easier if the SDK would just allow this to happen
automatically, either through improved compatibility with the 3rd-party
VSIX, or through end-to-end added support.

**Comment by RonakThakkar** [comment]
Hi,

I had same requirement in my project. I tried slowcheetah plugin that does
app.config transformation for console applications. It worked.

https://visualstudiogallery.msdn.microsoft.com/69023d00-a4f9-4a34-a6cd-7e854ba318b5

**Comment by abatishchev** [comment]
Yeah, it works. But how to do if as a part of build on build server?

**Comment by RonakThakkar** [comment]
Use msbuild to publish .csproj with deployonbuild set to true and provide path to pubxml file that contains credentials of azure websites where you wish to publish webjob

**Comment by abatishchev** [comment]
Will it transform app.config inside console app?

**Comment by ccuono** [comment]
To try to help make things clear: SlowCheetah does not work to transform app.config files with an automated deployment of a web job through a web application deployment to azure.

**Comment by brunobertechini** [comment]
I have it working including developer machine and VSTS automated build transformation without SlowCheeta.

Im using this extension in my developer machine: [https://marketplace.visualstudio.com/items?itemName=GolanAvraham.ConfigurationTransform](url)
This extension even transform when you use other configuration when debugging. It does that by modifying csproj with custom build tasks. After installing and use "Add config transformations" to your App.config (WebJob) you dont need the extension anymore.

I have the following scenario working:

* One Web Project 
* One WebJob Project (referenced by Web using the json config -- default)

I have a CI build configured in VSTS using the following parameters:
```
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=$(build.stagingDirectory) /p:AutoParameterizationWebConfigConnectionStrings=false
```

This is generating 02 WebDeploy Packages (Project.Web.zip and Project.WebJob.zip)

I am deploying only Project.Web.zip (as it includes the webjob as well)

In Release manager im using an extension to do config transformations:

* Extract zip file
* Execute transformation for all config files
* Archive folder again
* Deploy new archived to Azure AppService

This is working fine for quite a while.

If anyone needs any help please let me know

**Comment by carlmwright** [comment]
Just to highlight changes since the comment by ccuono. 

The current version of slowcheetah (Microsoft.VisualStudio.SlowCheetah : https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2043217-support-web-config-style-transforms-on-any-file-in) appears to transform webjob app.config files correctly during a publish of the parent web site.

**Comment by abatishchev** [comment]
But CI/CD scenarios are still out of support
