### ISSUE TITLE
FunctionInvocationException: MissingMethodException when reading bindings from table parameters

### ISSUE THREAD

**Issue by MatthewSteeples** [Azure/azure-webjobs-sdk#596]
It would appear that the storage library ([as of 6.1](https://github.com/Azure/azure-storage-net/blame/d4284edb04c9d6cb9112b1480da098c13c4ede4f/Lib/Common/Table/TableOperation.Common.cs)) has added a new optional parameter to the Retrieve method which, as they're all resolved at compile time, means that this code now can't find the method it's looking for. It's a source compatible change so recompiling would work, but in the meantime the NuGet references for the WebJobs SDK will need to limit which versions of the SDK they accept. The other disadvantage is that as soon as it's rebuilt then the limit will need to go the other way (and only accept 6.1 or greater) unless we can [persuade the storage team](https://github.com/Azure/azure-storage-net/pull/203) to add a method in for backwards compatibility.

**Comment by mathewc** [comment]
Thanks for pointing this out. We moved up to version 4.3 of the storage library in release, but we won't be able to move to 6.1 until we ourselves rev our major version number. We have an issue tracking all this - when we move to 2.0 we'll update all our dependencies to their latest.

**Comment by mathewc** [comment]
Closing this, since the SDK only supports up to version 5.0.2. In our upcoming 1.1.1 release, we've updated our package dependencies to declare version range [4.3.0, 5.0.2].

In our 2.0 release we'll be able to move forward to the latest new storage SDK version.

**Comment by advancedrei** [comment]
Hello, The storage team mentioned that this is fixed in Version 6.2 of the Storage binaries. Would it be possible to put out like a 1.1.2-preview that removes the NuGet version restriction and has a manual warning in the package notes to avoid specific Storage versions? That way you can get people on 6.2 without having to support a 1.1.2 final release, and without having to wait until the current code is ready for a 2.0 release.
Thanks!

**Comment by mathewc** [comment]
What we might try is running our tests on 6.2 as we did before. If (like the 5.0.2 version) all tests pass on that version as well, we could extend the version range to [4.3.0, 6.2] while keeping our dependency at 4.3.0. This would allow people to upgrade at their discretion.

**Comment by advancedrei** [comment]
Any word on this? Thanks!

**Comment by mathewc** [comment]
I've run all our tests against 6.2.0 - they all pass w/o any code changes. I'm OK with extending this package dependency range to allow 6.2.0. I'll let you know when I have an updated prerelease package for you to try.

**Comment by mathewc** [comment]
Ok, I've uploaded prerelease packages allowing upgrade to 6.2.0. Can you please try these and report back? Thanks. Version 1.1.2-alpha-10237 has the changes. Prerelease instructions [here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds).

**Comment by MatthewSteeples** [comment]
This issue has resurfaced with version 7 of the .NET SDK. They've removed the method again. This library will need to have the acceptable versions restricted as before.

**Comment by advancedrei** [comment]
Yep. Can we also please just get a WebJobs SDK release that is compiled to 7.0, so we don't have this problem anymore?

**Comment by davidebbo** [comment]
There are two very different things that should not be confused:

1. Restricting the list of acceptable version as @MatthewSteeples suggests: that really wouldn't accomplish much, as you still couldn't use 7.0 (you'd just get blocked in VS instead of runtime). In fact it would break some working scenario, as several people on [this thread](https://github.com/Azure/azure-webjobs-sdk/issues/631) reported success with 7.0.
2. Change the SDK to use Storage 7.0 as @advancedrei suggests: that I think is what we need to look into. That may cause some pain points for people expecting to use the much older 4.3, but we need to move forward, and in the end there is no way around it.

**Comment by advancedrei** [comment]
Can we add "Take to Storage Team out back for messing with the API without checking back compat?" to the list? We should probably also re-open the bug in the Storage SDK, and add a test so that the method does not go missing again.

**Comment by davidebbo** [comment]
Yes, please do open a Storage issue as well. It could be that it was unintentional and they'll fix it in an update once they know about it. /cc @pemari-msft?

**Comment by pemari-msft** [comment]
Sorry, but we had no intention of keeping the backwards compatible method long term. We added the workaround to 6.2 to unblock you because it was an accidental breaking change and should not have been included in 6.1. However, now that we've moved to 7.0 (a major release that has breaking changes) we've moved forward with the original plan. There is no contract of backwards compatibility according to semver when you have a major version release (so comments about taking the storage team "out back" regarding "messing with the API without checking back compat" are misguided at best). 

Taking a dependency on a new major version of the library places an onus on the party taking the dependency to update their code to account for any breaking changes (in this case, to recompile). Thanks!

**Comment by mathewc** [comment]
@pemari-msft is totally correct w.r.t. breaking changes and semver major/minor versioning. Those considerations are why this library remains at 4.3 - we'll only move forward to 7.0 when we **rev our own major version**, otherwise we risk breaking people. We removed or version restrictions to allow people to move forward to 6.2, but moving up to 7 is at their own risk.

**Comment by davidebbo** [comment]
I think what we should do is:

- keep SDK 1.1 on Storage 4.3 to avoid breaking changes
- rename our 1.2 pre-release to 2.0 and upgrade to latest storage (and other packages that are outdated). No breaking change issue since 1.2 was never released

**Comment by mathewc** [comment]
There are a bunch of bug fixes and other things included in the release that I'd like people to receive. If we expand scope on the release, it will make it harder for people to move forward and get those fixes.

**Comment by advancedrei** [comment]
@pemari-msft Sorry if you didn't like my statement, I probably could have worded it better. It's important to remember that the WebJobs team is the one currently taking the dependency, not me. I'm taking a dependency_ on a dependency_ that is significantly slowing down my ability to release new features to MY customers. I think it is important that MSFT employees keep this in mind when thinking about this type of issue.

Also, something to keep in mind is that, while you are right about SemVer, SemVer is not permission to just break stuff _without warning_. MSFT best practices of deprecating APIs (decorating the offending methods and not removing them till the next major release) do not appear to have been followed here. If Microsoft teams are breaking other Microsoft team stuff because they skipped process, then yes, a trip to the woodshed is in order. ;)

**WebJobs Team:** Building on what @davidebbo said, if you want to still be able to deliver bug fixes to 1.x customers, then I think you need to have different shipping branches and ship from them instead of "master". Maintain a 1.X branch that has a .nuspec file that limits storage to 4.3. Then create a 2.X branch that also delivers those fixes (or use master for 2.X), and has a .nuspec file that is on the very latest dependencies. That gives developers like me a choice. Right now my only choice is to not ship new features to my customers because I'm being artificially held back.

I hope that helps you all understand an outside perspective. Thanks for your help! :)

**Comment by mirobers** [comment]
@advancedrei Unfortunately, I don't believe that deprecation will work here. Marking Obsolete produces warnings at build time, which is precisely the moment at which the warnings are unnecessary (having now built against the new binary). What you need is a warning saying "you took a dependency on 7.0 but some of your existing dependencies may not support it". There isn't a good way to do this in general, other than simply taking the major version change as a sign that things could break in dependencies built against the 6.x (or earlier) libs.

Having said that, we'd like to avoid breaking the WebJobs scenario and we (the storage client team) will try to avoid such binary-only breaks in the future and make sure such changes when they do occur are well-documented even if they are not a compile-time break.

**Comment by davidebbo** [comment]
We'll focus on upgrading the SDK to use 7.0. Note that it will initially be in a pre-release 2.0 package that we would get on NuGet. No clear ETA yet on when it would become Released. Still, should be good enough to unblock people.

**Comment by mathewc** [comment]
Commit https://github.com/Azure/azure-webjobs-sdk/pull/709 has moved the SDK to the latest packages of all our main dependencies.

**Comment by advancedrei** [comment]
Awesome. ETA to NuGet?

**Comment by mathewc** [comment]
On our myget feed as 2.0.0-alpha-10313. We're going to try to get a prerelease up on Nuget soon.
