### ISSUE TITLE
Bound the version of Storage dependancy

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#604]
In nuspec, bound the version of Storage SDK to be >=4.3 and <=5.0

**Comment by mathewc** [comment]
Fixed. Verified and uploaded new build with fix to myget.

**Comment by softeering** [comment]
Hi Mathew,

Why has this been bound to <=5.0.0? Package on myget was working well with 5.0.2 and I'm now unable to install the 1.1.1-alpha-10182 in another project.
Error message is: 
Unable to resolve dependencies. 'WindowsAzure.Storage 5.0.2' is not compatible with 'Microsoft.Azure.WebJobs 1.1.1-alpha-10182 constraint: WindowsAzure.Storage (≥ 4.3.0 && < 5.0.0)'

FYI, Storage SDK version 5.0.0 doesn't even exist as a nuget package

Thanks

**Comment by mathewc** [comment]
Yes, intentionally bound to 5.0.0. I understand that 4.3.0 was the last version in the 4.0 major release band - basically we're dependent on that and we've been getting lots of complaints that VS is auto upgrading people to the latest 6.0 version which is breaking.

Now it might be the case that 5.0.2 also works, but we've done no testing on that. The safest thing to do is to cap at 4.3 which is what we test with. Thoughts? I'm open to relaxing this up by trial and error - i.e. if it turns out that some of the early 5 versions don't break things (to unblock you and potentially others). But we don't want to leave it unbounded as it was before.

**Comment by softeering** [comment]
Thanks

I understand but we really need to have it working with the 5.0.2 version to avoid a breaking change.
We've been using webjobs with Storage 5.0.2 since months now and we can't upgrade to the newest version because of the added dependency bounds.
I confirm that the 6.0.X doesn't work and I don't upgrade to this version because of this. However, the current highest working version is 5.0.2 (and not 5.0.0 - which doesn't even exist as a nuget package)

Could you please have a look at this before releasing the final version 1.1.1? Otherwise, we won't be able to use the new Webjobs SDK version created based on a support ticket we opened at Microsoft.

Thanks in advance Mathew

**Comment by mathewc** [comment]
I'll run our tests today on newer versions and get an updated package out that works to you.
________________________________

**Comment by softeering** [comment]
Sounds good
Thanks

**Comment by mathewc** [comment]
Ok - I've run full tests against 5.0.2 and have updated our package to allow this as well. The range is now (≥ 4.3.0 && ≤ 5.0.2). Please give this a try, thanks.

**Comment by softeering** [comment]
Thanks Mathew
