### ISSUE TITLE
Does the "Publish As Azure WebJob" do Xml Transforms?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk#608]
Hi :)

![image](https://cloud.githubusercontent.com/assets/899878/11836892/a682d5f8-a431-11e5-92f1-babfa34fe395.png)

When I use the "Publish as Azure WebJob" in visual studio, I don't think it's doing an xml transform on my `app.config`.

Can you folks confirm if it should be doing it, if i have the appropriate `app.release.config` file AND i've set the publish to be in `RELEASE` mode?

**Comment by mathewc** [comment]
No they are not. This is not WebJobs specific, but is due to the fact that VS doesn't support this for project types other than web. See [this VS UserVoice post](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2043217-support-web-config-style-transforms-on-any-file-in).
