### ISSUE TITLE
Can we downgrade 3x Singleton logging messages from INFO to DEBUG?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk#612]
Hi team :wave: 

I'm logging message from `ERROR` -> `INFO`. I'm noticing a fair bit of **Singleton** spam messages in this output. I feel that this info is not that relevant at an `INFO` level, but very important at a `DEBUG` level.

Could it be considered to drop the Singleton messages from `INFO` down to `DEBUG`?

These are the three messages I'm referring to:

```
[12/22/2015 22:49:53 > 944464: INFO] Waiting for Singleton lock (Snip....Listener)
[12/22/2015 22:49:53 > 944464: INFO] Singleton lock acquired (Snip....Listener)
```
and
```
[12/22/2015 22:49:53 > 944464: INFO] Renewing Singleton lock (Snip....Listener)
```

**Comment by mathewc** [comment]
From the WebJobs SDK standpoint, these Singleton logs are logged as Verbose, not Info. So if you don't want to see these, be sure you have the logging level set on your JobHostConfiguration.Tracing.ConsoleLevel to Info (which is the default). 

There might be some confusion here because there are 2 logging systems in play - the second is the Kudu WebJob host which is receiving the Console output from your Continuous WebJob exe - it interprets all output from the exe as INFO and outputs it to your log file.

**Comment by PureKrome** [comment]
Ah yes - confirmed! - **PEBCAK** 

*blush*
