### ISSUE TITLE
Timer triggers not firing or taking a long time to start

### ISSUE THREAD

**Issue by AnthonyDewhirst** [Azure/azure-webjobs-sdk#614]
I have been trying to use the Timer Triggers for 3 webbjobs that live on the same instance. When running locally, they fired the first time no problem. Then I deployed to my text env and everything was just fine. Then they started to not work at all locally and then when deployed, 2 webjobs started to fire after 20 minutes and the 3rd never fired. I have them set at "00:00:30" which I realise doesn't create a monitor by default. I am using the same dashboard credentials for local and for my test environments.
I decided to download the code from github and I have seen the same results when running locally. I commented all the code out of the sample program except the call to config.UseTimers and all the sample example except the 30s timer example. Again, I am using the same dashboard credentials as for my real project and the results are also intermittent. I have gone back to using a loop and thread sleep which is really not ideal so any help would be appreciated.

**Comment by mathewc** [comment]
Please see [this wiki page](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger) for more details and recommendations.

**Comment by AnthonyDewhirst** [comment]
Hi Mathew,

Thanks for the pointer. 
I can understand now why I am seeing issues. I had somehow used the same storage account in each of my environments, this will be fixed immediately.
Just to be sure, the page is saying that I don't need a storage account per web job, just per environment running the same web job, is this correct?
Out of curiosity, is this trigger name based on the name and namespace of the function?
How do you propose to deal with local devs running the webjobs where we all share the same storage account? (I.e., the string in the web.config is checked in and always pointing to the same place for local dev)

**Comment by mathewc** [comment]
Yes, if you have multiple developers all attempting to run the same job sharing a storage account, there will be lock contention. The lock ID is based  The scenario at that point is the same as if the function is running in production across multiple scaled out instances - there are multiple instances of the job host running, but only one will get the lock and run the function schedule. That's the behavior you want in production.

This issue is related to [this issue](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/25) where we added a new `JobHostConfiguration.IsDevelopment` property and corresponding `JobHostConfiguration.UseDevelopmentSettings()` method to configure things optimally for local development.

We are considering adding the ability to **disable locking** during local development. That would address your scenario - it would allow multiple devs to all be running the function concurrently.

**Comment by mathewc** [comment]
We've made changes that are available in the latest prerelease builds to address the issues you pointed out. You can [pull our latest prerelease package](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds) to try it out. We've made changes to ensure that for a particular HostId (which is 1:1 with your WebJobs project / fully qualified assembly name) all Singleton locks are isolated within that scope. Now normally you don't worry about the HostId - the SDK manages that for you and assigns one for you. This means that when doing local development, all devs are running with the same HostId and hence the lock contention.

The proposal is for devs to **use their own HostId** during local development. They can do this easily by adding a command line argument to their VS project (which will be stored in their csproj.user file). You can then modify your WebJob startup code to use this HostId if specified (but in production use the default ID):

```csharp
if (config.IsDevelopment)
{
    config.UseDevelopmentSettings();
    if (args.Length > 0)
    {
        config.HostId = args[0];
    }
}
```

You don't have to use the command line approach - you can set it however you want conditionally. With this approach there will no longer be any locking issues, and you'll also have Dashboard separation of invocations for each HostId.

**Comment by ayoubzghondi** [comment]
lll
l
ppk
