### ISSUE TITLE
Job failed due to exit code -2146232576

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-webjobs-sdk#616]
When running a web job in Azure, we get 'Job failed due to exit code -2146232576'. When debugging locally, the web job functions as expected. I read this may have something to do with Web Jobs in Azure does not support .Net 4.6.x yet, but the job still fails after restoring .Net version to 4.5.2.

**Comment by mathewc** [comment]
Yes, that error code corresponds to error "**0x80131700	     -2146232576	      CLR_E_SHIM_RUNTIMELOAD	      Failed to load the runtime**" as detailed in this [forum post](https://social.msdn.microsoft.com/Forums/en-US/e4ec7c82-8e87-41ab-ac06-2ba6362d141c/webjob-executable-cannot-be-started-failed-due-to-exit-code-2146232576?forum=windowsazurewebsitespreview). Your exe likely is still trying to load 4.6 for some reason - perhaps your rollback was partially unsuccessful?

**Comment by tedvanderveen** [comment]
All our code is now compiled against .Net 4.5.2 now and still we get the same error.
Is the Web Job runtime fully isolated from the 'parent' Web App (that is running .Net 4.6.1)?
Is there an ETA for the Web Job runtime to support .Net 4.6+? We were a bit surprised that the Web App engine does support the latest .Net version while the Web Job runtime does not.

**Comment by mathewc** [comment]
Your WebJob runs under the exact same environment as your Web App - any version of .NET that Web Apps supports is also supported by WebJobs. Perhaps there is some other issue with your job/references.

**Comment by tedvanderveen** [comment]
@mathewc We have our Web App running on .Net 4.6.1 successfully. So are you saying .Net 4.6.1 should also be supported bij WebJobs?

**Comment by mathewc** [comment]
Your WebJob runs **within** a WebApp - same environment. Perhaps there is some other assembly version issue that you have. Do you have a simple repro of this that you can share - like a git repo containing a simplified version of a WebJob exhibiting the problem?

**Comment by tedvanderveen** [comment]
I'm afraid I cannot share this code. But I'm not sure I understand you fully, does this mean we can run the WebJob on .Net 4.6.1 because the Web App does support it well? Or do we have to downgrade our corresponding WebApp to .Net 4.5.2 also if we want to use Web jobs?
This is the error output we see:
[01/05/2016 08:35:00 > 0d95a2: SYS INFO] Status changed to Initializing
[01/05/2016 08:35:00 > 0d95a2: SYS INFO] Run script 'spIDer.WebJobs.Monitoring.exe' with script host - 'WindowsScriptHost'
[01/05/2016 08:35:00 > 0d95a2: SYS INFO] Status changed to Running
[01/05/2016 08:35:00 > 0d95a2: SYS INFO] Status changed to Failed
[01/05/2016 08:35:00 > 0d95a2: SYS ERR ] Job failed due to exit code -2146232576

Is there more verbose logging output available from the WebJob runtime?

**Comment by tedvanderveen** [comment]
@mathewc Or am I missing something else maybe?

**Comment by mathewc** [comment]
I just did a quick test to verify that I can successfully deploy an SDK WebJob that targets .NET 4.6. I deployed it and it runs fine. So we might be focusing on the wrong thing w.r.t. the .NET version.

You might try starting your WebJob console exe directly from the command line using the [Kudu Console](https://github.com/projectkudu/kudu/wiki/Kudu-console) to see if more error information is written.

**Comment by tedvanderveen** [comment]
@mathewc When I use the Kudu console at {yoursite}.scm.azurewebsites.net to start the web job executable directly, I call:
D:\home\site\wwwroot\app_data\jobs\triggered\{webjobname}>{webjobname}.exe. The console returns no error, it just returns the cursor. Just to make sure nothing sits in the way from the Web App deployment, I deleted all the content from the wwwroot directory and re-deployed the Web Job and ran it again from the Kudu console. Same result.
Can I run our Web Job executable from the Kudu console with additional flags to get verbose logging output?

**Comment by tedvanderveen** [comment]
Finally resolved the root cause: .Net 4.6.1 is not supported. After downgrade to .Net 4.6 the Web Job is running again. Which I find a bit strange, as Web App does support .Net 4.6.1.

**Comment by rustd** [comment]
Closing as there is no bug here.

**Comment by tedvanderveen** [comment]
Sure it is not a bug, it's just inconvenient and unepected as Web Apps do support .Net 4.6.1. At least the docs should be more clear about this imho

**Comment by mathewc** [comment]
**Azure WebApps do not yet support .NET version 4.6.1**. That framework version is not yet installed on the hosting VMs. It should be supported in the next couple months, but isn't yet. In the mean time, if you change your WebJob to target 4.6 it will work. While your WebApp that targets it might load fine, if you were to try to use any of the new 4.6.1 APIs it would fail. I'm not sure why Console exes fail fast in this case.

I agree there should be somewhere in Azure docs where these limitations and release plans are communicated. There might be, but I'm not aware of it.

**Comment by davidebbo** [comment]
For reference: https://feedback.azure.com/forums/34192--general-feedback/suggestions/11070060-webjobs-executables-fail-when-targeting-net-4-6-1

**Comment by vip32** [comment]
now we are in 2017, is 4.6.1 supported?

**Comment by davidebbo** [comment]
Yes, it has been for a long time. We're currently on 4.6.2. So you likely have a distinct issue, even if the return code is the same.

**Comment by vip32** [comment]
ok thx, will investigate. it seems to be something in my code (as other jobs run fine)

**Comment by amafanga** [comment]
There is clearly a bug here. I have changed the framework version and I keep getting the same issue [10/15/2017 14:52:47 > eb4404: SYS ERR ] Job failed due to exit code -532462766

**Comment by davidebbo** [comment]
@amafanga that's a completely different error code, so unrelated to what this issue is tracking. Please isolate the repro scenario (starting with [these steps](https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues)), and open a new issue.

### Note to others: please do not add to this issue if you are getting an error code other than -2146232576. Thanks!

**Comment by kim3er** [comment]
Sorry to rise this thread from the dead. Are you supporting 4.7.2 yet?

**Comment by davidebbo** [comment]
@kim3er Not yet. See https://github.com/Azure/app-service-announcements/issues/89 and use the associated discussion thread if needed.

**Comment by kim3er** [comment]
Thanks @davidebbo!

**Comment by gmanvel** [comment]
We have a .NET 4.7 deployment (Web App + Web Job), but web job fails to start with the following in the logs

> [10/18/2019 13:29:05 > abf022: SYS INFO] Run script 'Workers.WebJob.exe' with script host - 'WindowsScriptHost'
> 
> [10/18/2019 13:29:05 > abf022: SYS INFO] Status changed to Running
> 
> [10/18/2019 13:29:06 > abf022: SYS ERR ] Job failed due to exit code -2146232576
> 
> [10/18/2019 13:29:06 > abf022: SYS INFO] Process went down, waiting for 60 seconds
> 
> [10/18/2019 13:29:06 > abf022: SYS INFO] Status changed to PendingRestart

Do we have to specifically target **.NET 4.7.2** for this to work ?

**Comment by samconn** [comment]
I tripped over something that I thought might be beneficial to the community ...

I was making some "improvements" to a working WebJobs application, which included moving our app.Config based configuration settings into a different system. Since there was nothing left in that file besides - what I thought!!! - was a superfluous `<supportedRuntime>` setting, I figured I'd just do a little cleanup and remove this unnecessary file.

Everything ran normal from within VS, but once deployed to Azure I started getting the ***-2146232576*** error.  

Retracing my steps I realized that the app.Config with the `<supportedRuntime>` might not be so superfluous after all. ;-}

I ran a couple tests, the first with just a correctly-formatted app.Config file without the runtime setting and the second with the runtime setting. The former failed ... the latter succeeded.

Here's my app.Config:

```<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    <!-- The following setting is ABSOLUTELY essential, and must match the FW of the deployable project.
         Failure to have an app.config with the correct setting will provoke the dreaded 
         "Job failed due to exit code -2146232576" error. -->
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
</configuration>
```
My apologies for the lengthy commentary ... hopefully this is helpful.

Sam.

**Comment by robert-shattock** [comment]
Posting to help others - error message does represent usage of an unsupported runtime.  In my case the console app we were deploying as a WebJob had a project TargetFrameworkVersion of v4.8.1

`<TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>`

And hence our app.config had the following:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8.1" />
    </startup>
</configuration>
```
It appears Azure WebJobs only support .NET Framework 4.8 currently (not 4.8.1) - https://learn.microsoft.com/en-us/answers/questions/1098266/support-for-framework-4-8-1-in-azure-webjobs

So in our case changing our app.config to have 4.8 instead of 4.8.1 fixed the issue

`        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />`
