### ISSUE TITLE
Do webjobs auto-rety when webjob starts, if it didn't finish correctly last time?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk#621]
I think I'm noticing that when a _scheduled_ webjob fails and stops, when we restart it later (for example, we publish a new fix) the webjob methods fire off asap.

for example.

i have a webjob with 2x methods:

```
    // NOTE: Run at 2:30am.
    public static async Task Foo1Async([TimerTrigger("0 30 2 * * *")] TimerInfo timer)
    {
        await FooAsync(new FooConverter());
    }

    // NOTE: Run at 2am.
    public static async Task Foo2Async([TimerTrigger("0 0 2 * * *")] TimerInfo timer)
    {
        await FooAsync(new bahConverter()
     }

```

When I check my logs, etc .. it looks like that it's starting asap if it didn't succeed previously. This (in effect) is firing off _both_ those methods at the same time (which causes problems for me).

Is my thinking here, accurate/correct?

If yes, are there any options to _not_ have this happening so when I restart (and it previous didn't work) it will _not_ auto-run. So it _only_ runs on those time slots.

(Or i messed up my cron times :disappointed: )

**Comment by mathewc** [comment]
`TimerTrigger` does schedule monitoring to keep track of execution times, and also to determine if it is **off schedule**. If a schedule is missed, the timer will fire on startup as you've noticed in an attempt to "catch up" [code here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs#L75). You can disable this per function by setting the `TimerTriggerAttribute.UseMonitor` property to `true`.

**Comment by kamranayub** [comment]
Just wondering, is it possible for TimerInfo to expose missed occurrences? For example, right now if it says `IsPastDue` I don't run my job because I don't know what time it was originally scheduled for that it missed. I assume that there could have been multiple occurrences missed, so perhaps it needs a list (MissedOccurrences). I don't know if you store that anywhere or could retrieve it to expose that though.

**Comment by mathewc** [comment]
That might be one option for making the handling of missed occurrences more configurable. If in addition to IsPastDue you also had the time the function last ran and the time of the missed occurrence, you could use arbitrary logic in your function to determine what to do, or whether to skip it.

**Comment by kamranayub** [comment]
That would be very helpful. In fact, right now I manually store a result in my database for all my scheduled jobs to say whether or not it finished "successfully" (based on my logic). Because I use that to perform relative date logic (i.e. get me all changed objects from some 3rd party API since I last successfully ran).

If I could store arbitrary (POCO) state with each run, that would be amazing--and would eliminate a dependency on storing my job results in my database.

**Comment by PureKrome** [comment]
Hi @mathewc - thank you kindly for the prompt reply :+1:  I'll give that a go :smile:

**Comment by mathewc** [comment]
@kamranayub Feel free to log a new issue for your suggestion if you wish.
