### ISSUE TITLE
Ability to use ScanContainersStrategy in Blob Trigger

### ISSUE THREAD

**Issue by justinpatten** [Azure/azure-webjobs-sdk#632]
After digging through the code, I saw that there is a blob listener that will scan the blob container instead of using the storage logs. However, it appears that it is only used when using a development storage account, which technically isn't even possible with the WebJob SDK.

Can there be a mechanism added, similar to IQueueConfiguration, to allow us to choose which strategy to use? I would be open to creating a pull request for this, but I want to know if it is even something that would be approved.

**Comment by mathewc** [comment]
Yes, the PollLogsStrategy is the default - that development storage check is old/out of date :) Note that the PollLogsStrategy does do an initial startup scan, then uses storage logs.

Can you explain your scenario a bit more? Is your goal to use one of the built in strategies, or to implement your own? The scan containers strategy is not the default due to perf issues with large blob containers.

**Comment by mathewc** [comment]
Please see the open (in progress) pull request for an update to our default strategy: https://github.com/Azure/azure-webjobs-sdk/pull/637. It is an attempt to increase performance in certain scenarios.
