### ISSUE TITLE
add unique user agent to all storage requests to be able to get logs server side

### ISSUE THREAD

**Issue by shobak101** [Azure/azure-webjobs-sdk#680]
to monitor and get insights about customer trends in using storage related operations (listening on blobs/ queues - blob outputs) and basically all storage requests that we control, we need to send a unique user agent header. This way we can collect metrics and logs from Storage server side.

**Comment by mathewc** [comment]
Can you please provide a full description of this work item?

**Comment by mathewc** [comment]
Regarding the PR for this issue: Since this is a global static setting, rather than doing it explicitly via StorageBlobClient/StorageQueueClient, I think you should instead do it in a single place on startup, e.g. via a JobHost static ctor or something. Note that we also want this to happen for Table storage as well, so doing it once centrally makes sense, rather than doing for each storage service.

**Comment by mathewc** [comment]
Also, I think you should remove the hyphen from the agent string "-AzureWebJobs" and use a space delimiter instead.

**Comment by mathewc** [comment]
This work is done.
