### ISSUE TITLE
Why you are not compatible with the latest version fo Azure Storage?

### ISSUE THREAD

**Issue by ricardopolo** [Azure/azure-webjobs-sdk#698]
Thanks!

**Comment by jefking** [comment]
This is a big issue: https://www.nuget.org/packages/Microsoft.Azure.WebJobs
WindowsAzure.Storage (>= 4.3.0 && <= 5.0.2)

Remove the <= 5.0.2 constraint; it affects projects that have the constraint where > 5.0.2.

We just went back a version in the WebJob SDK due to this (as a work around).

I am happy to do the pull request on this, if it is not intended behavior.

**Comment by davidebbo** [comment]
Dup of #565

**Comment by mathewc** [comment]
Update: we've just released version 1.1.2 of the SDK on Nuget.org. This version is a hotfix to 1.1.1 that removes the Storage version cap that we had in place. So if you upgrade to 1.1.2 you should now be unblocked to upgrade to later storage versions. You should be fine upgrading to 6.2 - I did a test pass on that and it looked good. I haven't tried 7.0 yet.

**Comment by ricardopolo** [comment]
😄

**Comment by mathewc** [comment]
FYI: We've released the [2.0.0-beta1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.0.0-beta1) prerelease on Nuget. In this version, we've moved completely to the latest Storage SDK version.
