### ISSUE TITLE
Blob-only Storage Account

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-webjobs-sdk#710]
When using the Webjobs SDK with a Blob storage account (not General purpose storage account):

![image](https://cloud.githubusercontent.com/assets/1633401/15027782/d2d53cec-121b-11e6-99ce-54897ad0938f.png)

The JobHost crashes trying to access the storage queue domain (which, in a Blob storage account doesn't exist.

**Comment by mathewc** [comment]
What is your scenario? The SDK requires queues because it creates some control queues to operate. For example, it creates a queue per unique JobHost to enqueue/process Dashboard invoke/replay requests, and to handle BlobTrigger functions (blobs are discovered and a message is enqueued to process them for scale out). This likely won't change.

**Comment by ealsur** [comment]
I'm using Blob-only Storage to store Hot or Cold data blobs that will later be passed on to Data Lake Store for analyzing.
This blobs are generated by periodically downloading dump logs from various sources and unifying their location on a single storage location (http logs from servers, error logs from apps, etc.).

I planned to use the Webjobs SDK to created functions with TimeTriggers that could persist information on set time intervals, each function accesing a different source/service and storing in different containers.

Blob-only storage is cheaper than General storage by the way :)

**Comment by ealsur** [comment]
@mathewc I'll give it a shot with what you suggested :) Thanks!

**Comment by mathewc** [comment]
Let me know how it goes. Note that `StorageAccountAttribute` can be applied at the parameter/function/class level.

**Comment by ealsur** [comment]
@mathewc the workaround using a "control" storage account for the JobHost and accesing the Blob-only storage account works :)

**Comment by mathewc** [comment]
Glad to hear it, thanks :)

**Comment by mathewc** [comment]
I created an issue https://github.com/Azure/azure-webjobs-sdk/issues/797 to track inprovements here.

**Comment by sharjeel-ahmed** [comment]
Looks like I have not understood where exactly the change needs to be done. I have created a new General Purpose storage account for all the Internal Queue processing. Lets call it X, my production blobs both Input and Output still remain in the same store, lets call it Y. 

This is the change I have made. 
```
JobHostConfiguration j = new JobHostConfiguration("X connection string");
JobHost host = new JobHost(j);
```            
My function is changed to 
 
`public static void resizeImage([BlobTrigger("tapntrack/{name}"), StorageAccount("Y Storage")] WebImage input,[Blob("tapntrack-thumbs/{name}"), StorageAccount("Y Storage")] out WebImage output)
`

But now it looks like the triggers are not being triggered at all.

**Comment by mathewc** [comment]
@sharjeel-ahmed What version of the SDK are you using? On further thought, while this pattern works for the other triggers, it might not actually work currently for BlobTrigger :( The other user's scenario above worked because he was just doing blob inputs/outputs to the other storage account, not trying to trigger on blobs.

**Details**: BlobTrigger works by leveraging storage blob logs. We have a shared component that monitors those logs looking for new blobs. I believe the issue you're running into is that currently that blob log scanner targets the main storage account only (your X above), so its not seeing the blobs. Again, this is only an issue currently for BlobTrigger due to its complicated underlying nature of blob log scanning => queue.

**Your Options**: The best option if it is possible for you would be to instead to write a queue message yourself every time you have a blob ready for processing, with the queue message containing the blob details. This is actually the pattern we recommend for people (more details [here](https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-storage-blobs-how-to/)). The QueueTrigger will work in the multi storage account scenario above. The other option would be for you to instead use a standard storage account for everything.

**Comment by mathewc** [comment]
@sharjeel-ahmed What version of the SDK are you using? Note that BlobTrigger relies on Storage blog logs, and there can be a delay in receiving those, (more details [here](https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-storage-blobs-how-to/)). Try a few more times to confirm that it isn't just a timing issue (i.e. you didn't wait long enough - sometines it can take minutes).

I expect the above to work.

**Comment by sharjeel-ahmed** [comment]
I have updated the SDK from nuGet so guess it is the latest.
I waited for long, dont see a change, when I debug my code I dont see it hitting any breakpoints nor do I see anything in the logs. Previously atleast I used to get error.

PS: I guess you have edited your previous comment where you mentioned that it is not possible with blobtriggers

**Comment by mathewc** [comment]
Specifically what version of the SDK do you have installed? What is the version in your packages.config?

Regarding my previous comment, yes I deleted it, since I looked into it more and multi-account should work.

As an experiment, can you try pointing your setup to the standard storage account first, removing the StorageAccount attributes, and test things out there to make sure your function, blob paths, etc. are all set up correctly? Once you have your scenario working against a standard storage account, you can add the StorageAccount attribute and try to point to the blob only account. This will help isolate the issue.

**Comment by sharjeel-ahmed** [comment]
The version 1.1.2 as I mentioned. 

Yes thats a good idea, I moved from storage(classic) to storage, the code worked well in classic, did not find anything in the documentation that i need to change for the new Azure Storage. 

Thanks for the tip, I will try what you said.

**Comment by sharjeel-ahmed** [comment]
Ok tried your suggestion. Works perfectly with a single storage General Purpose account. So does not look like a problem in the code itself.

**Comment by mathewc** [comment]
Thanks for confirming that. One last thing that you can check quick: that blob logs are actually enabled on that account. You should see a $logs container in your blob only storage account. Those are the logs that are polled.

If that is there, then we likely have a bug somewhere in this scenario.

**Comment by sharjeel-ahmed** [comment]
Yup I see logs, so looks like a bug!!
 
![image](https://cloud.githubusercontent.com/assets/3388155/17993988/7e6c5f4a-6b72-11e6-8771-839f0d9578b7.png)

**Comment by mamaso** [comment]
Hi @sharjeel-ahmed,

I ran this scenario using a secondary storage account that is blob only and was unable to reproduce the issue - the blob trigger ran & the blob was copied.
```c#
        public static void TestJob(
            [BlobTrigger("test/{name}"), StorageAccount("SecondaryStorage")] string input,
            [Blob("output/{name}"), StorageAccount("SecondaryStorage")] out string output
            )
        {
            output = input;
        }
```

Are you still seeing this issue with our latest nugets? https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds

**Comment by sharjeel-ahmed** [comment]
Sorry for a very delayed response. I was travelling.
So finally I got the above to work. I updated to the latest nightly builds and the only way I could make it work is to use a General Purpose account as the primary and use a Blob only secondary account at the function level as given in the above example. Thanks for the tip.

**Comment by darewreck54** [comment]
What version are you using?  I can't get StorageAccount attribute to work.  The webapp throws an exception at startup.

I created this issue: https://github.com/Azure/azure-webjobs-sdk/issues/1430
