### ISSUE TITLE
Fatal Exception Handling

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#766]
Currently we catch all exceptions resulting from the execution of a job method ([code here}(https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs#L100)), log them and continue.

However, for fatal exceptions (e.g. OutOfMemory) we should let the exception bubble up and bring down the host. In some other codebases we already have an "IsFatal" extension method that we should just employ here as well.

**Comment by amitfl** [comment]
We recently encountered a live site issue in which we got out of memory exceptions on requests that were processed by methods decorated with ‘ServiceBusTrigger’.
Although there was a fatal exception, the (continuous) webjob’s process stayed alive, and only marked the specific job requests as failed.
In our case, the out of memory exceptions were while trying to trace the error - making it even worse since there was no external evidence of the failure.

**Comment by brettsam** [comment]
#799 took care of this as well. We now elevate fatal exceptions, which will bring down the host by default.
