### ISSUE TITLE
Enrich TraceEvent to include invoked function name

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#784]
Here's how we're currently writing function invocation exceptions to Application Insights:
```csharp
var logger = container.GetInstance<IExceptionLogger>();
var traceMonitor = new TraceMonitor()
	.Filter(e => e.Exception != null)
	.Subscribe(f =>
		{
			foreach (var e in f.Events.ToArray())
			{
				logger.LogException(e.Source, e.Exception.InnerException ?? e.Exception);
			}
		});

config.Tracing.Tracers.Add(traceMonitor);
```
The problem is that `e.Source` always equals to `WebJobs.Execution`. Is it possible to replace it with respectful function name, or add a new property if this would be a breaking change otherwise?

**Comment by mathewc** [comment]
Yes, the Source property is used for other purposes. We could add more details like this not as top level properties of the general `TraceEvent` type (since that event is also used in cases where a function isn't even being invoked) but as additional data in the `TraceEvent.Properties` property bag which was added for that purpose.

The place in the code where we would add these properties would be in `TraceWriterFunctionInstanceLogger`, e.g. [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Loggers/TraceWriterFunctionInstanceLogger.cs#L27).

**Comment by abatishchev** [comment]
Yes, this sounds exactly what we're looking for!
Is this class extendable/pluggable by users, or the changes should be done on the SDK side first? If the former than is it available in current stable release, or we need wait version 2.0 to go live?

**Comment by mathewc** [comment]
The change needs to be made in the SDK itself, since we're emitting the event.

**Comment by abatishchev** [comment]
I see. How can we make it extensible? I'd rather spend more time on this than on what to put there by default. Every project likely will have their very own requirements here.

btw what is current schedule, when to wait version 2.0?

**Comment by mathewc** [comment]
We should just add the function name to the Properties collection. We might be able to leverage that in Functions. Currently in Functions we have our own custom trace writer that injects the function name.

**Comment by abatishchev** [comment]
Please add! This will significantly improve the readability of the telemetry (we write logs and exceptions to AI).

**Comment by brettsam** [comment]
`TraceEvent.Properties` will now include function information -- available properties found here: https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Loggers/TraceEventExtensions.cs
