### ISSUE TITLE
SingletonManager Lease Improvement

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#837]
We should investigate using a proposed lease ID when acquiring our blob leases in SingletonManager.TryAcquireLeaseAsync (code [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs#L366)). Currently when we loose a lease and try to reacquire it, we have to wait for the lease to expire. If we use the same lease ID, we'll be able to acquire it directly. This will improve startup times for the host.

E.g. we may just be able to use JobHost.HostId.

It's easy to see the existing issue. If you start/start a single instance of the Samples app (which uses Timers) back to back, you'll see the second time you start it up, there will be a delay before the timer listener can start up, because it is waiting to acquire the lease. If running with AZURE_WEBJOBS_ENV = Development, the default lease length is 15 seconds, so the delay will be a max of 7 seconds. However, when running in production, the delay can be up to 30 seconds. If the above fix works as intended, we should be able to reacquire our lost lease immediately on restart.

**Comment by lindydonna** [comment]
@mathewc Is talking to himself. He will fill out the customer scenario later OR will fix the bug first.

**Comment by brettsam** [comment]
One thing that's not mentioned above is that Functions puts the Host into Development mode when you are connected via the portal (and that setting remains until the host restarts, which could be a while). This means that your Singleton leases are reduced down to 15 seconds, greatly increasing the chance of a 409 under load. This change removes the need to shorten that lease time, which means they will always be 60 seconds.

I'm hoping it'll slightly help with #822 for those using Functions.

**Comment by brettsam** [comment]
We had a discussion a while back on this (see #913 for some of it) and came to the conclusion that the risk here was far greater than the reward. This was mostly to allow for faster turnaround during development, but it brought up a whole mess of issues that could potentially break. The major one being that only one host could be running on a machine at a time. In the Script world, we often have overlapping hosts -- so that would cause all kinds of issues. Closing this out as I don't think there's a great solution.
