### ISSUE TITLE
Functions show as running forever if end events are missing

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk#916]
Functions appear as running if end events are missing.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a C# function that awaits on a long `Task.Delay`
2. In Kudu, kill the host process (ideally, wait for the function to appear in monitoring before doing so)
3. The function will continue to show as running, indefinitely
 
![skypeteams-image](https://cloud.githubusercontent.com/assets/2507935/20449030/d5c6ba7c-ad9b-11e6-9e7f-effc4e16a6fe.png)

#### Expected behavior
The function should show as terminated (failed)

#### Actual behavior

Function shows as running.

**Comment by fabiocav** [comment]
@MikeStall, FYI

**Comment by MikeStall** [comment]
We need a heartbeat so we can tell the difference between Orphaned & Running.  This is how the WebJobs dashboard solves this.

**Comment by tim-schulze** [comment]
What is meant by "end events"?  We discovered a similar issue with some functions we developed that are showing as never ending in the invocation log-- some of these go back for days.  The confusing part is that our functions are simple and don't include loops/wait states so we don't understand why they wouldn't end normally since we aren't manually killing the host process.

**Comment by MikeStall** [comment]
@tim-schulze  - WebJobs (and Functions) record when the function starts and when it ends.   But if the process dies in the middle, before the function finishes, then it only has a "start" recorded and no "end".   Naively, that'd make it look like it was still running. WebJobs SDK handles this by emitting a periodic "heartbeat" that lets us know the function is still alive (this is a similar pattern to how Azure  Queue Messages know the msg is still being processed) .   Thus if we have no End time, but the heartbeat is "recent", we know the function is still running. If the heartbeat is stale, we know the function was abandoned. 

The bug here is that Functions is not doing this heartbeat.

**Comment by tim-schulze** [comment]
@MikeStall Thanks for the explanation, much appreciated.

**Comment by MikeStall** [comment]
Tracked by https://github.com/projectkudu/AzureFunctionsPortal/issues/843
